### ISSUE TITLE
404s

### ISSUE THREAD

**Issue by vanessayuenn** [electron/electronjs.org#1022]
This issue captures all the links that lead to nowhere (404) on the electronjs. When we finally clear out this list, we can look into incorporating the work done in #1023 into tests.

```
/OpenNewsLabs/autoEdit_2/blob/1.0.7/www.autoEdit.io (referrer: /apps/autoedit)
/history (referrer: /docs/tutorial)
/docs/tutorial/unity-launcher (referrer: /docs/tutorial/desktop-environment-integration)
/docs/README (referrer: /docs/tutorial/quick-start)
/docs/api/web-view (referrer: /docs/tutorial/security)
/docs/api/optional (referrer: /docs/api/app)
/docs/api/web-view-tag (referrer: /docs/api/web-contents)
/docs/api/structures (referrer: /docs/api/structures/crash-report)
/docs/api/structures/optional (referrer: /docs/api/structures/jump-list-category)
```

**Comment by sameoldmadness** [comment]
The first two links on [Developing Electron](https://www.electronjs.org/docs/development/README) page also lead to 404.

- Code of Conduct (https://www.electronjs.org/CODE_OF_CONDUCT)
- Contributing to Electron -> (https://www.electronjs.org/CONTRIBUTING)

**Comment by erickzhao** [comment]
@sameoldmadness Thanks for the heads-up!

**Comment by DCzajkowski** [comment]
Does this issue cover missing `/api/*/history` pages in the new docs or should I create a new issue?

**Comment by erickzhao** [comment]
@DCzajkowski The API history feature hasn't been implemented in the beta docs yet. Please file a new issue in the tracker here https://github.com/electron/electronjs.org-new!
