### ISSUE TITLE
Should we use greenkeeper-keeper?

### ISSUE THREAD

**Issue by zeke** [electron/electronjs.org#1046]
Greenkeeper is working well for us, but we have a handful of modules that update very often, namely `electron-i18n` and `electron-apps`. I'm thinking maybe we should set something up to ship Greenkeeper PRs automatically if they pass all checks, like [greenkeeper-keeper](https://github.com/greenkeeper-keeper/reference-instance).

## Pros

- Changes are shipped quickly
- Less monotonous work for humans
- Decreased likelihood of git conflicts in package.json

## Cons

- The site could break! We've seen this a few times with `primer`-related updates that we didn't have tests for.
- We'd have to maintain a new self-hosted service (unless we find a Probot or some other hosted service that does it for us)

What do folks think? Should we try it?

**Comment by MarshallOfSound** [comment]
At least for `electron-apps` if the tests pass and the deploy succeeds then I think it should automatically merge 👍 Other deps idk, might make sense to have a quick human sanity check on other deps 🤔

**Comment by zeke** [comment]
Wonder how we could scope it to specific deps... I was thinking a Probot would be appropriate but apparently [bots may not be able to do it yet](https://github.com/probot/ideas/issues/22#issuecomment-360582605).

**Comment by vanessayuenn** [comment]
What about if we use caret range for the deps we trust (e.g. `electron-apps`, `electron-i18n`, etc), and just run a cron job to do `npm update electron-apps electron-i18n` periodically, similar to the [update content script](https://github.com/electron/i18n/blob/master/script/update-source-content.sh) in the i18n repo? It should still run and pass all the tests, of course. That way greenkeeper will only open up PRs for major releases for those deps.

**Comment by zeke** [comment]
Love that idea, @vanessayuenn 👍

**Comment by vanessayuenn** [comment]
So I closed this issue via #1204, since the original concern has been addressed without the use of `greenkeeper-keeper`. But if y'all want to continue the discussion on said tool, feel free to repoen. 😸

**Comment by zeke** [comment]
🤘 I love the simplicity of #1204
