### ISSUE TITLE
Images not loading on Homepage

### ISSUE THREAD

**Issue by deadcoder0904** [electron/electronjs.org#1067]
Just change [this line](https://github.com/electron/electronjs.org/blob/master/views/apps/index.html#L43) from `data-src` to `src` & it'll work.

**Comment by ckerr** [comment]
Ahh I was about to report this and you beat me to it :smile:

**Comment by deadcoder0904** [comment]
Yeah I saw this couple of times now that I'm creating Desktop app. But figured why wouldn't anyone notice such a big thing 😂

Anyways thanks. Didn't want to send a PR for deleting 5 letters 😜
