### ISSUE TITLE
New releases not visible at https://electronjs.org/releases

### ISSUE THREAD

**Issue by ckerr** [electron/electronjs.org#1070]
1.8.2-beta.5 and 1.7.12, both released a few days ago, are not listed on https://electronjs.org/releases

**Comment by vanessayuenn** [comment]
It looks like we haven't gotten a greenkeeper PR for updating `electron-releases` for a while. The last update was done manually after the security patch (#1048), not sure if that has caused issues? 🤔  @zeke iirc something similar happened with `electron-apps` before, right?

**Comment by zeke** [comment]
Not sure why @greenkeeperio didn't pick this up, so I just bumped it manually: https://github.com/electron/electronjs.org/pull/1072
