### ISSUE TITLE
Italian translation has also code translated

### ISSUE THREAD

**Issue by DPDmancul** [electron/electronjs.org#1084]
In the italian translation of the website also the code in the references and in examples is translated.
Example: "BrowserWindow" becomes "FinestraBrowser" which is the correct translation in italian but it mustn't be translated because it is a class name.

**Comment by zeke** [comment]
Thanks for reporting this, @DPDmancul. We have a lot of translators joining the project who are unfamiliar with what should and should not be translated. We are working with Crowdin to find solutions to this problem of disallowing translation of certain pieces of content, but for now our best solution is to delegate proofreader status to certain people so they can help keep the translations correct.

Please let me know your Crowdin username and I will happily promote you to proofreader so you can administer these changes for Italian. Sound good?

**Comment by DPDmancul** [comment]
DPD-

**Comment by zeke** [comment]
Hey I don't see that username among the translators on the Electron project. Have you translated anything yet?

**Comment by DPDmancul** [comment]
No I didn't have got the account so I created it this morning.

Il 14/feb/2018 17:40, "Zeke Sikelianos" <notifications@github.com> ha
scritto:

**Comment by zeke** [comment]
@DPDmancul I'm not comfortable promoting brand new Electron translators to the proofreader role.
Please do some translation work on the Electron project on Crowdin first. After you've done so, comment back on this issue and we'll re-evaluate. Thanks for your understanding.
