### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by vinzruzell** [electron/electronjs.org#1085]
I would like to request for a Filipino Translation contribution thru github as per utopian.

**Comment by zeke** [comment]
Hi @vinzruzell. What's your Crowdin username?

**Comment by vinzruzell** [comment]
Hi...my crowdin user name is vinzruzell.
Thank you.

**Comment by zeke** [comment]
Hey I don't see that username among the translators on the Electron project. Have you translated anything yet?

**Comment by zeke** [comment]
Once you've actually made some translations on the project, please comment again on this issue and I'll change your status to proofreader. Thanks.

**Comment by vinzruzell** [comment]
Thank you for that
