### ISSUE TITLE
zero-downtime deployments

### ISSUE THREAD

**Issue by zeke** [electron/electronjs.org#1092]
In our current deployment setup, every merge to the master branch triggers a Heroku deployment to production. There's a brief period of a few seconds during this process when the website becomes unresponsive. I think we can use Heroku pipelines to prime a release so there will be zero downtime between deployments.

**Comment by BinaryMuse** [comment]
I've enabled [preboot](https://devcenter.heroku.com/articles/preboot) on the dyno; keeping an eye on things to see how it performs.

**Comment by BinaryMuse** [comment]
Seems to be working great!

**Comment by zeke** [comment]
👏 👏 👏
