### ISSUE TITLE
Make `lang` param more permissive

### ISSUE THREAD

**Issue by zeke** [electron/electronjs.org#1107]
- https://electronjs.org/docs/tutorial/security?lang=en-us does not work.
- https://electronjs.org/docs/tutorial/security?lang=en-US does work.
- https://electronjs.org/docs/tutorial/security?lang=en _should_ work.

cc @groundwater

**Comment by FranzDeCopenhague** [comment]
I can help on that

**Comment by FranzDeCopenhague** [comment]
What supposes to happen with a none translated region? For example Spanish from Argentina https://electronjs.org/docs/tutorial/security?lang=es-AR
My guess is redirecting to lang=es-ES

**Comment by zeke** [comment]
I would start by looking at how https://github.com/tinganho/express-request-language parses the accept-language header. As I recall it's pretty permissive, by which I mean you can give it a short string like `en` or a locale that is not supported, and it will pick the closest match. Maybe we can re-use whatever it's using.

**Comment by FranzDeCopenhague** [comment]
See above commit, I did apply a different approach. Based on the current Electron locales set, filter the lang out and redirect the request with the correct lang value.

* https://electronjs.org/docs/tutorial/security?lang=en-us redirect to https://electronjs.org/docs/tutorial/security?lang=en-US
* https://electronjs.org/docs/tutorial/security?lang=es-AR redirect to https://electronjs.org/docs/tutorial/security?lang=es-ES

**Comment by FranzDeCopenhague** [comment]
Verified that now works
* https://electronjs.org/docs/tutorial/security?lang=en-us
* https://electronjs.org/docs/tutorial/security?lang=en

**Comment by zeke** [comment]
🎉 Nice work, @FranzDeCopenhague

**Comment by 50Wliu** [comment]
I believe this broke Traditional Chinese.  `lang=zh-TW` now redirects to `lang=zh-CN`.

**Comment by FranzDeCopenhague** [comment]
I have fixed this issue with a new pull https://github.com/electron/electronjs.org/pull/1115

**Comment by FranzDeCopenhague** [comment]
@50Wliu @zeke Verified in production now https://electronjs.org/docs/tutorial/security?lang=zh-TW does not redirect
