### ISSUE TITLE
Add a team page

### ISSUE THREAD

**Issue by zeke** [electron/electronjs.org#1125]
Inspired by this: https://babeljs.io/team/

Electron is not just GitHub. There are Electron core teams at Slack, Microsoft, and other companies. Our maintainers team is nearly 150 people. We have over 600 translators. Let's make a page on the website to acknowledge the contributions of all these people.

**Comment by zeke** [comment]
It has been suggest that `/people` would be a good route name. This gives us flexibility to list members of whatever we're considering the "core team" as well as more casual contributors.

**Comment by zeke** [comment]
Also `humans.txt` is a cheeky alternative to `robots.txt` that I've seen here and there.

**Comment by bakhaa** [comment]
Hey. I am interested in this issue, and I would like to help you.

**Comment by erickzhao** [comment]
Closing this as we kind of have: https://electronjs.org/governance
