### ISSUE TITLE
2.0.0 release page is out of sync

### ISSUE THREAD

**Issue by pfrazee** [electron/electronjs.org#1131]
I just noted the https://electronjs.org/releases#2.0.0-beta.1 page has "Changed a [distro] thing" under MacOS and Linux and it looks like some other details are off. I recall seeing an earlier draft of the release that looked like that so maybe some cache invalidation needs to be forced.

**Comment by zeke** [comment]
Fixed it! https://github.com/electron/electron/issues/12012

Thanks, @pfrazee
