### ISSUE TITLE
Intro animation got wonky

### ISSUE THREAD

**Issue by zeke** [electron/electronjs.org#1133]
Somehow the initial position and opacity of the logo elements got messed up. See https://electronjs.org/

<img width="750" alt="screen shot 2018-02-22 at 9 23 57 am" src="https://user-images.githubusercontent.com/2289/36553789-2293bd2e-17b2-11e8-9f63-6020201dc9de.png">

I just noticed it. Haven't dug into what might have caused it.

cc @simurai

**Comment by simurai** [comment]
It's logo's way of saying: "Please replace me". :smile:

Something must've changed in Chrome/Safari". Firefox still seems to show it correctly.
