### ISSUE TITLE
Show app’s “last updated”

### ISSUE THREAD

**Issue by Zearin** [electron/electronjs.org#1148]
In the list of Electron apps, there is a `Added (x <time>) ago` bit of info in the long list view.

Many of these apps were added 2 years ago, which can give the appearance of staleness.  

Instead, I’d love to see this same info show when each app was last **updated**.

**Comment by zeke** [comment]
I like this idea.

For apps that have GitHub releases data, we could use the date of the most recent release. @Zearin do you want to give this a try?

**Comment by Zearin** [comment]
> For apps that have GitHub releases data, we could use the date of the most recent release. @Zearin do you want to give this a try?

Alas, I currently don’t have the free time to work on this. :(  

(Exhibit A: my 1 month delayed response.  Sorry about that!)

**Comment by parasg1999** [comment]
Hello, It's my first time here but I would like to work on this, is it still up for grabs?

**Comment by HashimotoYT** [comment]
@parasg1999 Go for it!

**Comment by parasg1999** [comment]
So I have tried to update the app list, the following are the results

When `latest_release` information is available
![Screenshot from 2020-05-30 03-50-27](https://user-images.githubusercontent.com/31986918/83310166-ca9e8780-a228-11ea-8503-82029513b7dd.png)

When `latest_release` information is not available
![Screenshot from 2020-05-30 03-50-46](https://user-images.githubusercontent.com/31986918/83310170-cbcfb480-a228-11ea-8ac0-e7b0b4c63520.png)

I was thinking about two options
1. Don't show `Latest Release` for cleaner look.
2. Show `Not Released` for information.

**Comment by HashimotoYT** [comment]
@parasg1999 Looks good, I think option with don't show the `Latest release` when they don't available more preferable and cleaner for me. Feel free to open PR for future discussion.
