### ISSUE TITLE
Remove dead apps

### ISSUE THREAD

**Issue by Zearin** [electron/electronjs.org#1149]
I’ve just spent a few minutes browsing apps, and I got a few apps that gave me a `404` error when I clicked their homepage (sometimes with no repo link, or anything else to otherwise try the app out).  

Please add some sort of periodic review to app’s URLs, and prune the dead weight.  (Browsing Electron apps _should not communicate the idea_ that Electron is “where app ideas go to die”—unless they’re Atom.)

**Comment by vanessayuenn** [comment]
Hey @Zearin, thanks for bringing this up. I agree that apps that are no longer available should be removed. Right now, we don't yet have a formal process for removing apps like [the one we have for adding them](https://github.com/electron/electron-apps/blob/master/contributing.md). So if you notice an app has been deprecated, feel free to open a PR addressing that in the https://github.com/electron/electron-apps repo.

**Comment by zeke** [comment]
I wrote up some documentation about how to remove apps: https://github.com/electron/electron-apps/pull/532

**Comment by Zearin** [comment]
Thanks, @vanessayuenn and @zeke ! :D
