### ISSUE TITLE
404 for /docs/README

### ISSUE THREAD

**Issue by maximtop** [electron/electronjs.org#1165]
On page https://electronjs.org/docs/tutorial/quick-start
The following route is returning a 404 HTTP status code: /docs/README

**Comment by sharadshriram** [comment]
@maximtop, Cannot reproduce the issue! Tested on Chrome and Edge browsers.

**Comment by TiagoDanin** [comment]
@sharadshriram Click in "official guides"

**Comment by vanessayuenn** [comment]
Closing due to duplication of #1022
