### ISSUE TITLE
Inline links don't work in documentation

### ISSUE THREAD

**Issue by evxn** [electron/electronjs.org#1205]
Clicking on links doesn't redirect anywhere. 
Examples:
"see webContents.send" 
https://electronjs.org/docs/api/ipc-main

"Forge comes with ready-to-use templates" 
https://electronjs.org/docs/tutorial/boilerplates-and-clis

The same is with security checklist here
https://electronjs.org/docs/tutorial/security

Tested in 
Chromium  61.0.3163.100 (Official Build)
and Firefox 57.0.4

**Comment by zeke** [comment]
Related: https://github.com/electron/electron/issues/12085
