### ISSUE TITLE
How can I use Worker(for multiple thread) in Electron 1.8.4?

### ISSUE THREAD

**Issue by whvirgil2015** [electron/electronjs.org#1217]
I'd like to use Worker [(Web-Workers)](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) under Electron 1.8.4，but `typeof Worker 
 `results in `undefined`.
So need I have to require or import some other packages? 
Since I thought the Worker-function should be included in Electron implementations.

**Comment by MarshallOfSound** [comment]
@whvirgil2015 Please raise Electron issues on the main Electron repo.  This is the repository for the website.

You need to ensure you are running that code inside a renderer process.

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
