### ISSUE TITLE
multiple displays: no obvious way to pick other monitors on MSWindows using BrowserWindow family classes

### ISSUE THREAD

**Issue by h3rb** [electron/electronjs.org#1226]
I'm interested in writing a game engine with Electron.  Some of the more advanced features of desktops involve picking the target monitor, 

I can't seem to find a way to tell a BrowserWindow to open fullscreen on any other monitor than the "1" monitor on windows.  It would be nice to be able to do that.  

It would also be nice to tell a BrowserWindow to resize / adapt to a target monitor/display #

**Comment by ckerr** [comment]
@h3rb, did you mean to file this issue at https://github.com/electron/electron/issues ? This electronjs.org repo is for the website

**Comment by h3rb** [comment]
Yes I misposted.  I will re-post over there soon.
