### ISSUE TITLE
code snippets are wrongly indented

### ISSUE THREAD

**Issue by zeke** [electron/electronjs.org#1227]
Compare: https://github.com/electron/electron/blob/717f55b01200a68439486716efe23b374bd03abe/docs/api/app.md

to 

https://electronjs.org/docs/api/app

<img width="731" alt="screen shot 2018-04-18 at 8 44 30 am" src="https://user-images.githubusercontent.com/2289/38942856-c9f2346c-42e4-11e8-85ac-881d2dd63815.png">

**Comment by snidelyhazel** [comment]
(Hi Zeke! I paired with Nhori on some of the "good first issue"-labeled issues on W/S/C Code Day. There were some that I'd found interesting/challenging that have been swirling in the back of my mind, so I decided to look into them.)

I found app.md per the issue description. The Javascript code inside the triple backticks seemed to be formatted correctly, i.e. no extraneous whitespace in the markdown. 

I viewed the source of /docs/api/app in the browser, and noticed that the rendered markdown was all indented by two spaces. This indentation is mostly irrelevant in the HTML, except in the pre elements for displaying Javascript code. I would speculate that the markdown renderer doesn't actually insert this indentation, rather it gets added by whatever is responsible for inserting the rendered markdown into a section element on the page. Do you have any idea where to find that code?

Apparently pre elements are sensitive to indentation in the HTML source:
https://www.sitepoint.com/everything-need-know-html-pre-element/#accidental-spacing

I think there are two options: 1. find the pre elements then remove the indentation imposed on their content, 2. stop indenting the surrounding document in the section element.

**Comment by zeke** [comment]
Hi @snidelyhazel! Thanks for jumping in on this. You are correct in thinking that the issue is not with the source file, app.md. I haven't investigated deeply,  but my suspicion tells me that this is something in our [hubdown](https://ghub.io/hubdown) module that converts markdown to HTML and adds syntax highlighting for code snippets. OR it could be a CSS issue.

**Comment by snidelyhazel** [comment]
It appears our suspicions were entirely incorrect and the issue was with the handlebars.compile function being passed an empty options parameter.

From http://handlebarsjs.com/reference.html:
> preventIndent: By default, an indented partial-call causes the output of the whole partial being indented by the same amount. This can lead to unexpected behavior when the partial writes pre-tags. Setting this option to true will disable the auto-indent feature.

It's a one-line fix! I'll commit and push it shortly.

**Comment by snidelyhazel** [comment]
Let's see how the tests go!

Check it here: https://github.com/electron/electronjs.org/pull/1310

**Comment by snidelyhazel** [comment]
So what I did looks right on my local version of electronjs.org I'm running

![image](https://user-images.githubusercontent.com/30618085/44005281-a9a46b16-9e25-11e8-8b44-505cdc3c9dfe.png)

but I'm having problems with the Travis CI build again, and this time I don't know what to do with the error message.

![image](https://user-images.githubusercontent.com/30618085/44005285-d6559842-9e25-11e8-8345-ef421e902e2a.png)

Thanks in advance for any insight you can provide!
