### ISSUE TITLE
Language detection is wrong

### ISSUE THREAD

**Issue by tbarbugli** [electron/electronjs.org#1229]
When using Chrome (both regular and incognito mode) I get PT-BR as default language. My browser is set to english, I don't speak the language and I am browsing from US :)

Interesting fact: if I use Safari I get English as default language.

**Comment by tbarbugli** [comment]
Looks like the bug is related to how the `Accept-Language` is used. 

For example in this case:

`Accept-Language: en,it;q=0.9,it-IT;q=0.8,it-CH;q=0.7`

The content returned is in italian which is exactly the opposite of what the header is telling.

Google Chrome allows you to specify this via Settings -> Advanced -> Languages

**Comment by zeke** [comment]
Curious. Are you still seeing this behavior, @tbarbugli ?

If so, it will probably need to be resolved in the [express-request-language](https://ghub.io/express-request-language) modul, or the [accept-language](https://ghub.io/accept-language) module that it depends on.

cc @tinganho
