### ISSUE TITLE
Display stable API docs on /docs/all page

### ISSUE THREAD

**Issue by zeke** [electron/electronjs.org#1239]
https://electronjs.org/docs/all#modules-for-the-main-process is currently referring to the `inAppPurchase` API which exists in `electron@beta` but not `electron@latest`.

This page should be updated to display stable docs, not beta. And in the beautiful future, users should be able to choose a specific version. Follow https://github.com/electron/i18n/issues/288 for updates on that effort.

**Comment by fabiospampinato** [comment]
`https://www.electronjs.org/docs/all`, which was in my opinion the single best thing about the docs, got deleted entirely.

Can it be restored? It's much more difficult to explore the docs without an "all" page.

**Comment by zeke** [comment]
I agree that was a very useful page. I'm not active on this project any more, so I don't have context on why this page was removed. My guess would be that its massive size caused performance issues, but again I don't know.

cc @electron/wg-ecosystem

**Comment by fabiospampinato** [comment]
Did this get implemented? If so does anyone have the new link?
