### ISSUE TITLE
remove or update vulnerable `hoek` dependency

### ISSUE THREAD

**Issue by zeke** [electron/electronjs.org#1241]
It's a dev dep, so it's not on fire.

I thought #1235 might do the trick, but it didn't.

```
$ npm ls hoek
electronjs.org@2.0.0 /Users/z/git/electron/electronjs.org
└─┬ browser-sync@2.23.7
  ├─┬ chokidar@1.7.0
  │ └─┬ fsevents@1.1.3
  │   └─┬ node-pre-gyp@0.6.39
  │     └─┬ hawk@3.1.3
  │       ├─┬ boom@2.10.1
  │       │ └── hoek@2.16.3  deduped
  │       ├── hoek@2.16.3 
  │       └─┬ sntp@1.0.9
  │         └── hoek@2.16.3  deduped
  └─┬ localtunnel@1.8.3
    └─┬ request@2.81.0
      └─┬ hawk@3.1.3
        ├─┬ boom@2.10.1
        │ └── hoek@2.16.3  deduped
        ├── hoek@2.16.3 
        └─┬ sntp@1.0.9
          └── hoek@2.16.3  deduped
```

![image](https://user-images.githubusercontent.com/2289/39539922-04149b8c-4df6-11e8-986f-72caff8ce42c.png)

cc @ckerr

**Comment by codebytere** [comment]
generally, how are 2nd or 3rd level dependencies dealt with? would we update a top-level dependency and hope it gets updated too?

**Comment by zeke** [comment]
> would we update a top-level dependency and hope it gets updated too?

In this case yes I tried that in #1235 without digging, but it didn't bring `hoek` up to date.

**Comment by codebytere** [comment]
Fixed in master.
