### ISSUE TITLE
new URL structures

### ISSUE THREAD

**Issue by zeke** [electron/electronjs.org#1244]
Lets simplify the URL path structure so addresses are cleaner, easier to read, easier to remember, and easier to type.

## Current URLs

This is what we have now:

- `/docs`
- `/docs/tutorial`
- `/docs/api`
- `/search`
- `/search?q=ipc`
- `/search/docs?q=ipc`
- `/search/npmPackages?q=ipc`
- `/search/repo?q=ipc`

## Next Steps

This is what I think we should do next:

- Retire `docs` by splitting into `tutorials` and `api`.
- Rename `npmPackages` to `packages`.
- Rename `repos` to `apps`

URLs:

- `/api`
- `/tutorials`
- `/search`
- `/search?q=ipc`
- `/search/api?q=ipc`
- `/search/tutorials?q=ipc`
- `/search/packages?q=ipc`
- `/search/apps?q=ipc`

## Long-Term Goals

Where I think we should end up one fine day:

Flatten searches for different types: `/search/whatever?q=foo` becomes `/whatever?q=foo`

- `/search?q=ipc`
- `/apis?q=ipc`
- `/tutorials?q=ipc`
- `/packages?q=ipc`
- `/apps?q=ipc`

And landing pages for each type:

- `/apps`
- `/packages`
- `/api`
- `/tutorials`

**Comment by tibiii** [comment]
What about the `/docs/development` section?
