### ISSUE TITLE
OpenCollective widget blocked by AdGuard AdBlocker

### ISSUE THREAD

**Issue by zeke** [electron/electronjs.org#1247]
Hey @piamancini, just noticed that our [/donors](https://electronjs.org/donors) page wasn't loading for me in Chrome desktop. 

<img width="281" alt="screen shot 2018-05-09 at 2 27 29 pm" src="https://user-images.githubusercontent.com/2289/39840916-f86590f2-5395-11e8-9edc-8400596c7f67.png">

The culprit appears to be this extension: https://chrome.google.com/webstore/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg?hl=en

It was definitely working until very recently, so something must have changed in the OpenCollective embed thingy, or in that extension.

**Comment by zeke** [comment]
cc @HipsterBrown who [started recently](https://twitter.com/hipsterbrown/status/988434496344215552) at @opencollective 👋

**Comment by HipsterBrown** [comment]
@zeke I'll add it to my Bug Fix Fridays list. 😄

**Comment by HipsterBrown** [comment]
@zeke I haven't been able to recreate this behavior after installing that Chrome extension. Could you provide some more details about your settings for the extension and/or a screencast of the behavior?

**Comment by zeke** [comment]
Made a little screencast https://youtu.be/zX5zShEsPDI

**Comment by TiagoDanin** [comment]
![image](https://user-images.githubusercontent.com/5731176/39960765-e386a976-55fe-11e8-8141-8e878dd99faf.png)

The same with the filters:
- ABP Japanese Filters
- French filter
- Adblock-Persian list
- Liste FR

**Comment by zeke** [comment]
This seems to be fixed now, so I'm closing it.
