### ISSUE TITLE
OpenCollective widget cause flashback in ScrollBar

### ISSUE THREAD

**Issue by TiagoDanin** [electron/electronjs.org#1250]
**Summary**

https://youtu.be/aJ5siBZbNSs

Only while loading the page/ifranme (OpenCollective).

-----
URL: [electronjs.org/donors](https://electronjs.org/donors)
Type: bug

**Comment by zeke** [comment]
Love the soundtrack! 🎹 🎷 

cc @piamancini @HipsterBrown

**Comment by HipsterBrown** [comment]
@TiagoDanin @zeke I deployed a fix to the widget code that I believe fixed this issue. Let me know if you still see this scrollbar behavior.

**Comment by TiagoDanin** [comment]
@HipsterBrown Thanks.
Closed: Problem solved.
