### ISSUE TITLE
Use Algolia instantsearch

### ISSUE THREAD

**Issue by zeke** [electron/electronjs.org#1256]
Let's take the working demo at https://github.com/electron/electron-algolia-index and integrate it into the website!

Steps:

- Create a new file in `/scripts`, using one of the existing scripts there as a starting point.
- Invoke that new function from [`scripts/index.js`](https://github.com/electron/electronjs.org/blob/master/scripts/index.js), e.g. `require('./search')()`
- Add containers divs like `#search-box` and `#hits`  to the main layout `views/layouts/main.html` and/or the footer partial `views/partials/footer.html`
- Use the existing `electron-apis` index for `indexName` for now. We can move to multiple indices later (See https://github.com/electron/electron-algolia-index/issues/1)
- Style it up a bit, probably from scratch. DevTools element inspection to the rescue! Or use [demo.css](https://github.com/electron/electron-algolia-index/blob/master/demo.css) as a starting point.

**Comment by echjordan** [comment]
https://community.algolia.com/instantsearch.js/v2/widgets/pagination.html

For future pagination needs!

**Comment by zeke** [comment]
This is happening in https://github.com/electron/electronjs.org/pull/1248 -- keep  👀 on that for updates.
