### ISSUE TITLE
fix display of parentheses for right-to-left languages

### ISSUE THREAD

**Issue by zeke** [electron/electronjs.org#1258]
This is a followup to https://github.com/electron/electronjs.org/pull/1254

A few things are still quirky on RTL pages, like parentheses. Here's an example from the [Arabic /releases page](https://electronjs.org/releases?lang=ar-SA):

<img width="500" alt="screen shot 2018-05-21 at 9 00 51 pm" src="https://user-images.githubusercontent.com/2289/40341450-1c0de7b8-5d3a-11e8-9b5d-ac5ee8087640.png">

Possible ways to solve this:

- https://stackoverflow.com/questions/5741522/brackets-displays-wrongly-for-right-to-left-display-style
- `&rlm;` tag
- http://rtlcss.com
- https://www.npmjs.com/package/flipcss

**Comment by snidelyhazel** [comment]
Recommendation: add dir="auto" to surrounding section elements, like &lt;section class="page-section" dir="auto"&gt;. I think the browser should automatically detect the language of the content of an element with dir="auto" based on the characters used, then select an appropriate direction on a per-section basis. Sections that are still in English will be left-to-right, and fully translated sections in Arabic would be right-to-left.

Bidirectional text in HTML: https://www.w3.org/International/articles/inline-bidi-markup/index
Bidirectional text in Unicode: https://www.w3.org/International/articles/inline-bidi-markup/uba-basics

I'll try this out and let y'all know how I go.

**Comment by zeke** [comment]
Sounds good, @snidelyhazel! Feel free to open a WIP PR whenever.

**Comment by zeke** [comment]
@snidelyhazel thanks again for digging into this. Can you open a pull request that makes some of these exploratory changes? That will make it easy for folks to preview the effects of the change.
