### ISSUE TITLE
Emoji how a string not how a emoji

### ISSUE THREAD

**Issue by HashimotoYT** [electron/electronjs.org#1265]
In the documentation, the emoji can be seen as text, not as emoji.

Found in [About Electron](https://electronjs.org/docs/tutorial/about) page:

![v1](https://user-images.githubusercontent.com/24681191/40625179-85681038-62b9-11e8-8913-08e8ee8824b2.png)

**Comment by zeke** [comment]
This will be fixed by https://github.com/electron/hubdown/pull/6

**Comment by zeke** [comment]
This hasn't landed on the site yet because of a strange new test regression. https://github.com/electron/electronjs.org/pull/1268

I will close this once the emojis are displaying in production.

**Comment by HashimotoYT** [comment]
Fixed.
![default](https://user-images.githubusercontent.com/24681191/41990050-01e17652-7a4a-11e8-9450-c8731cdc08aa.png)
