### ISSUE TITLE
Smoke test new search in multiple browsers

### ISSUE THREAD

**Issue by zeke** [electron/electronjs.org#1272]
I noticed some `-webkit` prefixed styles in the search styles. We should make sure the search works and behaves as expected on multiple browsers. Namely Firefox and Safari.

![image](https://user-images.githubusercontent.com/2289/41045649-0e7bf90c-69a9-11e8-82ab-c9ab0f8a6052.png)

**Comment by echjordan** [comment]
Partially addressed in 5b3e36f64b6924de7a75594a3e09b533ed9dd68e
