### ISSUE TITLE
Improve styling of search matches

### ISSUE THREAD

**Issue by zeke** [electron/electronjs.org#1274]
We're highlighting the text that matched the user's query, but the current styles are a bit jarring. Let's do something more subtle like a light background color, or an underline, or italics, or some combination thereof.

![image](https://user-images.githubusercontent.com/2289/41045791-67f42d9c-69a9-11e8-945e-c2f4b60ef5ec.png)

**Comment by echjordan** [comment]
The latest: 
![screen shot 2018-06-07 at 11 52 26 am](https://user-images.githubusercontent.com/29494303/41120057-4a8c55d6-6a49-11e8-8f4b-75dae9e155bb.png)

**Comment by zeke** [comment]
Looking good 👍 

![screen shot 2018-06-18 at 11 38 13 am](https://user-images.githubusercontent.com/2289/41555297-1d958ce0-72ec-11e8-886e-32c5bf5a5549.png)
