### ISSUE TITLE
Not all PR references in release notes are getting linked

### ISSUE THREAD

**Issue by zeke** [electron/electronjs.org#1287]
https://electronjs.org/releases#3.0.0-beta.1 has references to multiple PRs, but they're not all getting linked.

![image](https://user-images.githubusercontent.com/2289/41733625-46ddfcfa-7539-11e8-9be6-1517caf08a0e.png)

**Comment by zeke** [comment]
The code that does this lives here:

https://github.com/electron/releases/blob/0b0bf2d77af9ef4b21846c092081134e831993e0/script/collect.js#L142-L151

**Comment by snidelyhazel** [comment]
(While I'm waiting to hear back about some of the other issues I took a look at, I decided to see what else I could do.)

Some of the source data that the regular expression in line 150 is parsing has spaces between the pull request number and the endline or multiple pull request references on the same line.

Either the regular expression should be modified to handle those cases or the source data should be formatted to work with that regular expression; I suggest the former. I'll play around with regular expressions and see what I come up with to solve those cases not being linked.

**Comment by snidelyhazel** [comment]
Actually, looking at the existing regular expression that's used to parse the release info, ```/ #(\d+)$/gm```, I'm wondering if there's a reason we need to look for the end of the line immediately following the pull request number? If we chuck the $ and go with ```/ #(\d+)/gm```, it finds all the linkable pull requests successfully.

**Comment by zeke** [comment]
> If we chuck the $ and go with / #(\d+)/gm, it finds all the linkable pull requests successfully.

Good call, @snidelyhazel. I think @HashimotoYT came to the same conclusion, and the fix has landed in https://github.com/electron/releases/pull/18

**Comment by zeke** [comment]
I'll verify and close this once we are using an updated version of the `electron-releases` module, which should happen [automatically](https://github.com/electron/electronjs.org/blob/e714dc04c0df26f3bc179095ead83a1005a70a01/package.json#L20) within the next hour.

**Comment by codebytere** [comment]
This appears to be resolved!
