### ISSUE TITLE
Some searches do not find API results

### ISSUE THREAD

**Issue by timfish** [electron/electronjs.org#1293]
Love this new feature!

I tried searching for some API docs and they weren't found. It looks like these API pages are in the index but the tokenizer doesn't work very well with camel case and/or text which isn't surrounded by whitespace?

![image](https://user-images.githubusercontent.com/1150298/41769696-6e89eb7e-7610-11e8-9028-336bdcbdd9da.png)

![image](https://user-images.githubusercontent.com/1150298/41770642-1cbdd6cc-7613-11e8-9599-ec79b6c2cb0d.png)

![image](https://user-images.githubusercontent.com/1150298/41769803-c6fac530-7610-11e8-9c7b-75a63328841a.png)

**Comment by zeke** [comment]
Thanks for reporting!

**Comment by schontz** [comment]
To add to this, it seems like search results are duplicated and the first result doesn't have the proper hash anchor. For example, searching 'copy' gives you these top 2 results:

1. contents.copy() at https://electronjs.org/docs/api/web-contents#web-contentscopy
2. contents.copy() at https://electronjs.org/docs/api/web-contents#contentscopy

The second one is the correct link. The first one brings you to the top of the page.

**Comment by schontz** [comment]
Also, if you click on the result title the link is followed. Clicking on other parts of the search results causes the results to disappear.

**Comment by HashimotoYT** [comment]
We deployed new indices of search, which contains very many new data. Please @ mention me if you still see this error.
