### ISSUE TITLE
German translation done by bots??

### ISSUE THREAD

**Issue by Brain-Gamer** [electron/electronjs.org#1295]
Today when I was looking up something in the docs I noticed that there was a German translation for electron which is very incomplete. So I thought I would help improve it and translate / check as much as I can afford to because I really like electron and want to make it easier for people who don't speak English native or good enough to understand everything (even though every programmer should).

So I looked over some parts of the German translation and noticed that a big amount of it was just translated by one user (who hasn't listed German as a preferred language) with some sort of a bot or online translator because the translations were inconsistent and pure rubbish.

Also the parts which are translated correctly never got approved (only 10 words got approved in total).

Are there any ideas to stop behavior like this and approve more translations?

**Comment by zeke** [comment]
Thanks for letting us know, @Brain-Gamer. The best solution we have to date is to promote trusted folks to proofreader status so they can help smooth out any issues with the translations in their language. If you're using Crowdin now, please send me your Crowdin username and I can look into giving you proofreader status. Thanks again for noticing and for your offer to help.

**Comment by codebytere** [comment]
We haven't gotten a response to our questions in our comment [here](https://github.com/electron/electronjs.org/issues/1295#issuecomment-403608045). With only the information that is currently in the issue, we don't have enough information to take action. In this event, i'm going to go ahead and close this but can reopen should you follow up with more info!
