### ISSUE TITLE
Missing escape HTML in release view

### ISSUE THREAD

**Issue by Toinane** [electron/electronjs.org#1296]
When I go to release view, you can see this : 

<img width="833" alt="capture d ecran 2018-07-16 a 15 15 44" src="https://user-images.githubusercontent.com/7584391/42760581-33077b3a-890b-11e8-853c-35bfa1207c0e.png">

I suppose the data isn't escaping 😄

**Comment by zeke** [comment]
Thanks for reporting! This would need to be solved here: https://github.com/electron/releases/issues/17

**Comment by TruptiM18** [comment]
Can I work on this?

**Comment by zeke** [comment]
Hey @TruptiM18 thanks for chiming in, and apologies for the delay getting back to you.

@pierreneter started working on this, but a solution hasn't been shipped yet. Please take a look at https://github.com/electron/releases/pull/19 -- I think the best way to solve this is with a small patch to the `hubdown` module. I've added a comment about it on that PR.

**Comment by zeke** [comment]
This issue was resolved by changing the release notes to wrap the `<input>` tag in backticks (`) so it is treated as code instead of an input element.
