### ISSUE TITLE
i18n | Site header can't fit text properly

### ISSUE THREAD

**Issue by rogi27** [electron/electronjs.org#1305]
Hello, as a translator of :electron: Electron, I noticed a little, but annoying bug with the website menu.
Some languages that using words longer than default causing problems with navigation menu on top of the website.

Is there any way to fix that problem?

![2018-08-09_17-46-51](https://user-images.githubusercontent.com/10144091/43906643-71d4839a-9bfc-11e8-99bd-34d262ac53c0.png)
![2018-08-09_17-47-21](https://user-images.githubusercontent.com/10144091/43906644-71f61b86-9bfc-11e8-8355-e486a6b3285c.png)

**Comment by zeke** [comment]
Thanks for reporting. And thanks for translating too!

**Comment by Voknehzyr** [comment]
Maybe we can just take away that "Electron" label from logotype for small displays? 🤔

**Comment by zeke** [comment]
☝️ I like that idea. It doesn't fully solve the problem but it's a start.
