### ISSUE TITLE
Electron Documentation for PRs has broken link to Code Owners

### ISSUE THREAD

**Issue by snidelyhazel** [electron/electronjs.org#1312]
I noticed on the Electron Documentation for Pull Requests
https://electronjs.org/docs/development/pull-requests#approval-and-request-changes-workflow
![image](https://user-images.githubusercontent.com/30618085/44074044-eca2e376-9f4b-11e8-878b-64f70e984373.png)

a broken link intending to provide a list of Code Owners that points to https://github.com/orgs/electron/teams/code-owners.
![image](https://user-images.githubusercontent.com/30618085/44074063-fd628de2-9f4b-11e8-8b5f-7dedbc348ba8.png)

It wasn't immediately obvious where the link should point.

**Comment by 50Wliu** [comment]
Looks like that link only works if you're a member of the Electron org.

**Comment by snidelyhazel** [comment]
Is that the desired behavior? If that info shouldn't be available to the public, is there something else it could redirect to rather than a 404 page? Some kind of join/login prompt?
