### ISSUE TITLE
HTTP 500 loading scripts/index.js

### ISSUE THREAD

**Issue by mauris** [electron/electronjs.org#1320]
As with the title, HTTP 500 is showing for scripts/index.js. I believe this is also breaking the "Apps" search filtering feature. 

![screenshot 2018-09-12 12 14 29](https://user-images.githubusercontent.com/996939/45421616-7daa0480-b685-11e8-85f2-502170297f9e.png)

From console:
 - GET https://electronjs.org/scripts/index.js 500 (Internal Server Error)
 - Refused to execute script from 'https://electronjs.org/scripts/index.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by MarshallOfSound** [comment]
I manually redeployed and it didn't fix it, I also can't reproduce the issue locally.

cc @zeke not sure what's going on here

**Comment by zeke** [comment]
Investigating...

> Refused to execute script from 'https://electronjs.org/scripts/index.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by zeke** [comment]
This is now fixed and deployed. Thanks for reporting, @mauris 🍰
