### ISSUE TITLE
Improve organization of /docs page

### ISSUE THREAD

**Issue by codebytere** [electron/electronjs.org#1354]
http://electronjs.org/docs at present is a bit cluttered and difficult to parse through; it would be great if we could consider a new visual organization of this data.

**Comment by mbabatunde** [comment]
Hi, I'm interested in helping out with this. What type of visual organization would you like to see with the new docs page?

**Comment by codebytere** [comment]
@mbabatunde hi, this is a great question 😁 I don't have a specific thing in mind, so if you have suggestions or ideas we can figure it out together!

**Comment by mbabatunde** [comment]
@codebytere Sorry for this late response! I've been busy with schoolwork, but I plan to work on this over the weekend. 

As for suggestions, does the idea of a drop down menu for those links seem viable?

**Comment by mbabatunde** [comment]
Maybe a navigation bar on the left hand side would be better?

**Comment by jdfwarrior** [comment]
I would agree with the side navigation. I'd be willing to help with this as well. I, personally, would love to have a side navigation on the individual API pages specifically that would provide a list of sections and MAYBE a list of the functions and such as well. I'm specifically thinking about things like `BrowserWindow`, having sections in a side nav to quickly jump to Instance Methods, Static Methods, Events, etc. It's a pretty long page to scroll through looking for what you want.

Anyone else still interested in working on this?
