### ISSUE TITLE
My (with electron develloped) application is not centered when I put it into the Mac-OS-Autostart.

### ISSUE THREAD

**Issue by ndsvw** [electron/electronjs.org#1355]
I wrote this small application [https://github.com/ndsvw/Unofficial-Qwant-web-search](https://github.com/ndsvw/Unofficial-Qwant-web-search) , but I noticed something.

When I put this application into the Mac-OS-Autostart (System-Settings -> Users and Groupd -> ...), I realized that the application is not centered when it starts automaticly.

![ohne titel2](https://user-images.githubusercontent.com/21332313/45914082-1425b500-be40-11e8-8fc6-aaeecb2fe3b4.png)
![ohne titel](https://user-images.githubusercontent.com/21332313/45914083-14be4b80-be40-11e8-9e49-1d23ff55eb3b.png)

Is it a bug or am I doing sth wrong?
(Mac OS High Sierra 10.13.6)

**Comment by codebytere** [comment]
Thanks for reaching out!

You've opened an issue on the repo for the Electron website, which doesn't contain the code for making Electron applications. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
