### ISSUE TITLE
Display install commands for apps on npmjs

### ISSUE THREAD

**Issue by HashimotoYT** [electron/electronjs.org#1457]
Need add a install command for npmsjs apps, on the app page.

Example:

```
npm install -g appname
```

If you would take this you can use this two examples:
https://github.com/electron/electronjs.org/blob/c5bafce27b1f14747e374e5e11fc44fdcbe70768/views/apps/show.html#L106-L118

Property for npm apps: `app.npmPackageName`

**Comment by zeke** [comment]
Apps I know off that are npm-installable: https://ghub.io/vmd, https://ghub.io/electron-api-demos

**Comment by mariolo1985** [comment]
Hello - I hope it is ok with me opening a PR for this issue.
