### ISSUE TITLE
Language selection not always sticking

### ISSUE THREAD

**Issue by BinaryMuse** [electron/electronjs.org#1463]
I discovered this while researching https://twitter.com/nanhopper/status/1055174419021291522.

I'm on Chrome 70.0.3538.67.

1. Open an incognito window and browse to https://electronjs.org/languages
2. Note in the developer tools that the `language` cookie is set to `en-US`
3. Choose another language in the list (I chose Spanish)
4. Note that the cookie value is now `es-ES`, but the site is still in English and the "(current selection)" indicator is next to English

Interestingly, I was not able to reproduce this on Firefox 63.0 or Safari 11.1 (13605.1.33.1.2) using similar steps. Also, I seem to recall that the very first time I chose a non-English language it worked fine, but then when I chose English again the incorrect behavior started — but I'm unable to reproduce this experience.

**Comment by BinaryMuse** [comment]
I strongly suspect this is due to https://github.com/electron/electronjs.org/pull/1449

**Comment by MarshallOfSound** [comment]
Fixed in #1465
