### ISSUE TITLE
Breaking Changes document is difficult to find

### ISSUE THREAD

**Issue by ckerr** [electron/electronjs.org#1582]
A couple of issues:

1. It's not shown on the `Documentation` page

2. ~~Also, if someone knew of such a document but didn't know where to find it, searching for `breaking changes` on the website returns a link to https://electronjs.org/docs/tutorial/planned-breaking-changes which is a 404.~~ This is tracked now in https://github.com/electron/electronjs.org/issues/1594

**Comment by BinaryMuse** [comment]
I discovered today that this is listed on [the docs page](https://electronjs.org/docs) under "API Reference" -> "API Contract"

**Comment by BinaryMuse** [comment]
This is the relevant data in `electron-i18n`:

```json
      "/docs/api/breaking-changes": {
        "locale": "en-US",
        "slug": "breaking-changes",
        "category": "api",
        "categoryFancy": "API",
        "href": "/docs/api/breaking-changes",
        "githubUrl": "https://github.com/electron/electron/tree/master/docs/api/breaking-changes.md",
        "crowdinFileId": "4278",
        "isTutorial": false,
        "isApiDoc": true,
        "isDevTutorial": false,
        "isApiStructureDoc": false,
        "title": "API Contract",
```

**Comment by nornagon** [comment]
Additionally, I think we should be showing the most recent `master` version of the breaking changes document on the website, rather than the document from the most recent stable. It's useful to know ahead of time what's going to break.
