### ISSUE TITLE
search results are not based on the same Electron version as docs

### ISSUE THREAD

**Issue by ckerr** [electron/electronjs.org#1594]
3.0.x is the current stable branch, so https://electronjs.org/docs is showing the 3.0.x docs.

However, when I search for "breaking changes" in the search entry field, the result of "Planned Breaking API Changes (3.0)" with a link to https://electronjs.org/docs/tutorial/planned-breaking-changes shows up. This file was moved between 2-0-x and 3-0-x, so that link is a 404.

So, things that were changed between these versions won't be discoverable through search. Also, things that were removed (such as `tutorial/planned-breaking-changes`) will give false matches.

**Comment by ckerr** [comment]
Somewhat related: https://github.com/electron/electronjs.org/issues/797

**Comment by HashimotoYT** [comment]
We deployed new indices of search, which contains very many new data. Please @ mention me if you still see this error.
