### ISSUE TITLE
build difficulty

### ISSUE THREAD

**Issue by maddhruv** [electron/electronjs.org#1607]
Whenever I am trying to make any changes in the html templates - `views`
the changes are not reflected in the build

**Comment by zeke** [comment]
are you running the server with `npm run dev`?

**Comment by maddhruv** [comment]
Yes

**Comment by zeke** [comment]
It looks like nodemon is not configured to watch for changes to `.html` files: https://github.com/electron/electronjs.org/blob/03f1a81f1cca717646d3ef0de35035530696c1c4/nodemon.json#L2

**Comment by maddhruv** [comment]
Even if I add `html` in watch
the changes are not occuring

**Comment by maddhruv** [comment]
no matter if `html` is down there or not
the fresh `dev` run should build from the available html!
which is not

**Comment by maddhruv** [comment]
@zeke is there any update on this?

**Comment by BinaryMuse** [comment]
@maddhruv It's possible you were being bitten by the service worker, and were being served cached pages. Do you still have this issue on the latest `master`? (If you haven't run the site locally since we removed it, you might need to refresh a couple times for the worker to be fully unregistered.)

**Comment by HashimotoYT** [comment]
Closing due to no response. Please reopen if you still see this problem
