### ISSUE TITLE
Markdown tables in some translated docs are not rendered correctly

### ISSUE THREAD

**Issue by BinaryMuse** [electron/electronjs.org#1999]
1. Browse to https://electronjs.org/docs/tutorial/electron-timelines
2. Change to another language

Expected: we see the translated document if it exists, and default to English otherwise

Observed: the page 404's

**Comment by HashimotoYT** [comment]
Need merge https://github.com/electron/i18n/pull/565, it should fix it.

**Comment by BinaryMuse** [comment]
Hm I thought those were supposed to auto-merge. 🤔 I'll look into that next week, for now I merged manually. I think automatic processes should take over now.

**Comment by HashimotoYT** [comment]
Okay, we have another problem, table not rendered correctly on translated docs (maybe related to i18n repo who convert docs, but we have also a table on [about page](https://electronjs.org/docs/tutorial/about), and it's render correctly):

![2019-01-30 22 27 05](https://user-images.githubusercontent.com/24681191/52010521-6bb6ea00-24de-11e9-9d1d-a821b21177f3.png)
