### ISSUE TITLE
Updated release notes on github aren't reflected at electronjs.org

### ISSUE THREAD

**Issue by ckerr** [electron/electronjs.org#2112]
The release notes for 5.0.0-beta.1 and -beta.2 were updated yesterday after some minor bugfixes in Clerk and release-notes (https://github.com/electron/clerk/pull/23, https://github.com/electron/electron/pull/16887). However these changes aren't being mirrored at electronjs.org.

For example,

https://github.com/electron/electron/releases/tag/v5.0.0-beta.1 begins:

```
Release Notes for v5.0.0-beta.1

Breaking Changes
* Upgraded to Chromium 70.0.3538.79. #15405

Features
* Added activate option to webContents.openDevTools. #13852
* Added app.commandLine.hasSwitch() / app.commandLine.getSwitchValue(). #16282
* Added fileMenu / viewMenu / appMenu roles. #16328
* Added ipc-message and ipc-message-sync events to webContents. #16468
* Added preload-error event to webContents emitted when preload script fails (parse error, unhandled exception, etc.). #16411
```

But https://electronjs.org/releases/beta#5.0.0-beta.1 begins this way:

```
Release Notes for v5.0.0-beta.1

Features
* Added activate option to webContents.openDevTools. #13852
* Added preload-error event to webContents. #16411
* Added a way to query for system colors on MacOS via systemPreferences.getSystemColor(). #16248
* Added about panel customization on linux. #15658
* Added additional remote APIs filtering. #16293
```

**Comment by HashimotoYT** [comment]
All data fetches from `e/releases` repo, which cannot be updated due to a broken night tag. It's should be fixed when `e/releases` can find broken nightly.

**Comment by BinaryMuse** [comment]
This resolved itself as @HashimotoYT mentioned it would.
