### ISSUE TITLE
☂ Primer CSS and "Basecoat" updating tracking issue

### ISSUE THREAD

**Issue by HashimotoYT** [electron/electronjs.org#2258]
# Process

This issue track a process for #757 about updating Primer and "Basecoat" styles packages to newer versions. Updating to `@primer/css` npm package, for now, not planned, for more information read "Why not bump it by add @primer/css?" section.

## List

| Package Name                        | Task Owner   | PR  | Status  | Notes |
| ----------------------------------- | ------------ | --- | ------- | ----- |
| primer-css/variables                |              |     |         |       |
| primer-css/mixins                   |              |     |         |       |
| primer-css/base                     |              |     |         |       |
| primer-css/type                     |              |     |         |       |
| primer-css/buttons                  |              |     |         |       |
| primer-css/filter-list              | @HashimotoYT |     | CLAIMED |       |
| primer-css/tooltips                 |              |     |         |       |
| primer-css/flex-table               |              |     |         |       |
| primer-css/utitilies/utilities      |              |     |         |       |
| primer-css/utitilies/normalize      |              |     |         |       |
| basecoat/variables                  | `wg-website` |     | BLOCKED |       |
| basecoat/scss/mixins/breakpoints    | `wg-website` |     | BLOCKED |       |
| basecoat/scss/mixins/grid           | `wg-website` |     | BLOCKED |       |
| basecoat/scss/mixins/clearfix       | `wg-website` |     | BLOCKED |       |
| basecoat/scss/mixins/grid-framework | `wg-website` |     | BLOCKED |       |
| basecoat/scss/layout                | `wg-website` |     | BLOCKED |       |
| basecoat/scss/type                  | `wg-website` |     | BLOCKED |       |
| basecoat/scss/grid                  | `wg-website` |     | BLOCKED |       |
| basecoat/scss/utility               | `wg-website` |     | BLOCKED |       |

#### For Primer packages:

1. Claim a package in this issue.
2. Find the same package in
   [primer repository](https://github.com/primer/css/tree/master/src).
3. Copy-paste styles into `./public/styles/primer/<name of package>.scss`
4. Add first line with link to source, use tag instead branch name. Example:
   `https://github.com/primer/css/blob/<tag>/src/<package name>/<package name>.scss`
5. Change import statement in `./public/styles/index.scss`
6. Run the website and check if nothing changed with styles.
7. Open up a PR

#### For Basecoat packages:

Process for updating "Basecoat" packages for now not tracks.

## Potential gotchas

This section takes updated when I or someone find an error.

## Why not bump it by add @primer/css?

Looks now Primer uses a single package instead of small packages, we can simply add `@primer/css` and take a needed style. But it still looks very risky, mostly if we have an error when updating `@primer/css`, we unable to fix it by updating styles locally. For now, I think we need manually port styles to repository instead of using npm version (but I'm open for discussion 💬).

### Why need this pretty small script?

This script created for check if we are lagging behind the version Primer what published to npm. If it's true we need to manually update styles. All Primer styles files should be live in `./public/styles/primer` folder.

---

Yes, this been inspired by "Jest TypeScript migration issue". 😃

**Comment by co16353sidak** [comment]
would love to take up a package, please assign `primer-css/variables` to me 🥇 
@HashimotoYT @BinaryMuse
