### ISSUE TITLE
duplicate api search results

### ISSUE THREAD

**Issue by bughit** [electron/electronjs.org#2488]
![image](https://user-images.githubusercontent.com/895588/56826301-e49db780-6829-11e9-8363-af1cd35e1055.png)
https://electronjs.org/docs/api/browser-window#winsetparentwindowparent
https://electronjs.org/docs/api/browser-window#browser-windowsetparentwindow

The second anchor is bad.

**Comment by HashimotoYT** [comment]
We deployed new indices of search, which contains very many new data. Please @ mention me if you still see this error.
