### ISSUE TITLE
The link color of the home page buttons

### ISSUE THREAD

**Issue by AM-77** [electron/electronjs.org#2499]
On firefox quantum 65.0.1
The link color of the home page buttons does not change when hover over it. -- Bad UX --
![Screenshot from 2019-04-30 10-57-00](https://user-images.githubusercontent.com/18232579/56951553-7104ee80-6b38-11e9-9492-9324c811a7af.png)

**Comment by HashimotoYT** [comment]
Fixed on master

**Comment by AM-77** [comment]
The same issue on the [apps page](https://electronjs.org/apps?category=developer-tools) on .PRIMER-REMOVE-ME .filter-item.selected when a category is selected.
