### ISSUE TITLE
docs search for "additionalArguments" does not return any results

### ISSUE THREAD

**Issue by bughit** [electron/electronjs.org#2596]
https://electronjs.org/docs?q=additionalArguments

it's documented here: https://electronjs.org/docs/api/browser-window

**Comment by ckerr** [comment]
I agree this would be useful to have. We don't currently have anyone available to work on this but if someone wants to contribute a patch an @ me I would be happy to review it.

**Comment by CoderHArsit** [comment]
hello sir,
the last comment is quite old but I want to know is there any work which I could contribute for the organization. I have a quite good knowledge in html , CSS and Java script. I am a newbie here and didn't make any contribution before.
It would be grateful of  you to give me an opportunity to work with you,
Thank you
for contact Gmail me at hs8449865663@gmail.com
