### ISSUE TITLE
internal auto-bump dependencies aren't being bumped by dependabot

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electronjs.org#2809]
| Dependency | Version on NPM | Version on Website | Backlog |
| --- | --- | --- | --- |
| electron-i18n | 1.1566.0 | 1.1558.0 | 8 |
| electron-apps | 1.7544.0 | 1.7533.0 | 11 |
| electron-api-historian | 1.7.0 | 1.6.0 | 1 |
| electron-releases | 3.177.0 | 3.176.0 | 1 |

Current view on dependabot dashboard:

![image](https://user-images.githubusercontent.com/6634592/61914050-ff003380-aef3-11e9-82f4-3320ceb277ce.png)

Unclear what's preventing it bumping them 🤔

**Comment by HashimotoYT** [comment]
Closing due to fixed.
