### ISSUE TITLE
Electron's website refers to Electron as both a library and a framework on its website

### ISSUE THREAD

**Issue by jbis9051** [electron/electronjs.org#2905]
From https://electronjs.org/

> Electron is a framework for creating native applications with web technologies like JavaScript, HTML, and CSS

From https://electronjs.org/docs/tutorial/about

> Electron is an open source library developed by GitHub

Which is it? Framework or library? Either way, it should probably be consistent throughout the website.

Also, regardless of the outcome, that second quote should probably say 'open-source' for clarity, not 'open source' (it's an adjective).

----

Orignal Issue: https://github.com/electron/electron/issues/19951

Referencing: https://chat.stackoverflow.com/transcript/message/47138497#47138497

**Comment by jbis9051** [comment]
Any updates on this urgent issue?

**Comment by pushkin-** [comment]
imo, framework is the more appropriate term

**Comment by bandantonio** [comment]
It seems like the issue is no longer relevant as the [tutorial](https://electronjs.org/docs/tutorial/about) page no longer exists. All other pages refer to Electron either directly (as is, just "Electron") or as a "framework".
