### ISSUE TITLE
Cookie documentation out-of-date

### ISSUE THREAD

**Issue by uallmight** [electron/electronjs.org#3254]
## Issue

As of version 7+ of electron setting a cookie requires to set the expiration date. [electron/electron issue](https://github.com/electron/electron/issues/20688)

## Work to Be completed

Update the [Cookie API Document](https://github.com/electron/electron/blob/master/docs/api/cookies.md) to relect that as of version 7+ users are required to pass the `expierationDate` property when setting a cookie.

**Comment by zcbenz** [comment]
I'm closing this issue since it is a bug of cookies API instead of a documentation problem.
