### ISSUE TITLE
Update /community page to today state

### ISSUE THREAD

**Issue by vhashimotoo** [electron/electronjs.org#3528]
Per @erickzhao message in Slack. Opened to track eyes on this.

**Comment by bnb** [comment]
pulling context from #4693:

Today, the Electron community page was referred to in the context of Node.js's website redesign and community page. In that context, I took a look at it and realized there are some things that we may want to rethink.

- Currently, we still point people to Atom's Discourse page. 
- We don't point to the subreddit. 
- We may want to to consider auditing either our consumption of the awesome-electron repo _or_ submit PRs to remove outdated content. In the `videos` section, the first video listed is `Getting Started with Electron 1.x` which will end up misleading end-users.
