### ISSUE TITLE
setFeedURL documentation does not match TypeScript types

### ISSUE THREAD

**Issue by NaridaL** [electron/electronjs.org#3780]
According to https://www.electronjs.org/docs/tutorial/updates#implementing-updates-in-your-app

I should be able to call `autoUpdater.setFeedURL("this is a string")`.

![image](https://user-images.githubusercontent.com/10828874/78162440-2a55fd80-7447-11ea-821c-5a93f71bcdcd.png)

**Comment by erickzhao** [comment]
Hey @NaridaL! Thanks for the report (and sorry for the delay).

See https://github.com/electron/electron/pull/23298 for a fix to this. For future reference, please note that all the website's docs live in the main `electron/electron` repository, so docs-related issues should be filed there!
