### ISSUE TITLE
Add a table of contents to documentation pages

### ISSUE THREAD

**Issue by TheRolfFR** [electron/electronjs.org#3867]
Hello everyone, 

I have been working with Electron for a ling time now. I often refer to documentation and I noticed I spent a lot of time looking for a specific item before finding it. For example the [BrowserWindow](https://electronjs.org/docs/api/browser-window) is very long.

I cloned the repo and noticed you just render the markdown. 

I know I am reopening an issue but thy can't you analyse it in order to create a table of content? You could put it in a collapsible panel in order not to take more place.

I don't know how to code on your website but **I made a CodePen with a preview** of what it could look like with your style :
[https://codepen.io/TheRolf/full/wvKWOYK](https://codepen.io/TheRolf/full/wvKWOYK)
The demo is interactive, you can click the "Table of Contents" title to expand or collapse the table of content.

The script algorithm behind however is not very complicated. I could help. Just parse the markdown to create a hierarchy with sections, sub sections and platform/deprecated labels.

Thanks for reading!

**Comment by erickzhao** [comment]
Currently working on updating our i18n package so that the data needed to make this happen is easier to access from the website code:
https://github.com/electron/i18n/pull/1349

**Comment by Judy-sspu** [comment]
Cool!
