### ISSUE TITLE
Update Symphony logo on Homepage

### ISSUE THREAD

**Issue by bnb** [electron/electronjs.org#3908]
The current Symphony logo seems to be an older version of their branding. It's also currently squished: 

![image](https://user-images.githubusercontent.com/502396/80637155-83a45300-8a2c-11ea-9b94-a82964a0679b.png)

Their newer logo (screenshot from their website, which fits in better with the rest of the wordmarks:

![image](https://user-images.githubusercontent.com/502396/80637195-9028ab80-8a2c-11ea-972a-9f88ee3ee47a.png)

**Comment by HashimotoYT** [comment]
That section doesn't more exists
