### ISSUE TITLE
setHighlightMode on search but not on page

### ISSUE THREAD

**Issue by luis-pato** [electron/electronjs.org#3917]
Hi.

I have been looking for the documentation on how to set an 'active' state to the tray icon when is it open.
When i search the docs (using the search input) for something like 'highlight', as you can see on the image, i get a result for `tray.setHighlightMode`.
![image](https://user-images.githubusercontent.com/42058106/80812566-7fad3800-8bc8-11ea-867f-2396893cc25b.png)

When i click on this result i am sent to the tray documentation page ( [url](https://www.electronjs.org/docs/api/tray?q=highlight#traysethighlightmodemode-macos) ), but there i cannot find any information about the `setHighlighMode` method.

Also, when i try to use this method on my app i get an error:
![image](https://user-images.githubusercontent.com/42058106/80812751-dadf2a80-8bc8-11ea-8de8-fa48f5127adc.png)

I am guessing this method doesn't exist anymore, but maybe i am wrong and the documentation is somewhere else.
Anyway, i thought i would report this problem so we can improve it.
😉

**Comment by erickzhao** [comment]
`setHighlightMode` was removed in Electron 7 (see https://github.com/electron/electron/pull/19202). I'm not too sure why it still appears in the search box, but thank you for the report! Will give try to give this a look. 🙇

**Comment by erickzhao** [comment]
This should be fixed now. The problem lied with an issue with our Algolia index package: https://github.com/electron/algolia-indices/pull/131
