### ISSUE TITLE
Sharing Beekeeper Studio?

### ISSUE THREAD

**Issue by rathboma** [electron/electronjs.org#4154]
Hey Electron team,

We have a pretty successful FOSS project built with electron - beekeeperstudio.io, we think it's a great example of what can be accomplished using Electron -- and it's a fairly easy codebase to look through for aspiring developers.

Firstly - thank you for building and supporting the platform. Is there a good way to share Beekeeper with the broader Electron community on the website?

Thanks either way, Matthew

**Comment by HashimotoYT** [comment]
Please see [`electron/apps`](https://github.com/electron/apps) and [`CONTRIBUTING.md`](https://github.com/electron/apps/blob/master/contributing.md#adding-your-app) for how to add own app.
