### ISSUE TITLE
Chrome dev-tools in Electron don't support changing variables

### ISSUE THREAD

**Issue by cythrauL** [electron/electronjs.org#4172]
I am using electron 4.2.12

I'm opening the Chrome developer tools in my application, setting a breakpoint, and trying to change the value of javascript variables in the local scope.

I've tried changing them in the console (where the variable correctly resolves) and in the 'scope' dialogue which opens in the 'sources' tab whenever you hit a breakpoint.

I believe this can be done in Chrome, but it doesn't appear to work in Electron.

My variable changes in the console, but does not change in the Scope dialogue, and when I continue execution, the variable remains unchanged.

**Comment by HashimotoYT** [comment]
Electron 4 is EOL. Also please notice that repository tracks only errors for the Electron website, if you have problems with Electron itself please open the issue in the [electron/electron](https://github.com/electron/electron/issues) issue tracker.
