### ISSUE TITLE
Add Twitter Card Image

### ISSUE THREAD

**Issue by HashimotoYT** [electron/electronjs.org#4200]
Currently, that shows a blank image for blog posts or releases page:

![Безымянный](https://user-images.githubusercontent.com/24681191/86847635-4f48b500-c0b5-11ea-8454-1043b2a7690b.png)

As an example, this is ESLint and NodeJS:

![Безымянный](https://user-images.githubusercontent.com/24681191/86847771-8c14ac00-c0b5-11ea-9b1e-6de12f662b5b.png)

![Безымянный](https://user-images.githubusercontent.com/24681191/86847996-e7469e80-c0b5-11ea-8cda-5465bef8b15a.png)

More optimal is to show the Electron logo if any other image is not provided to the requested resource.
For start you can read the Twitter docs: https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/markup, code for showing the image can be found here: https://github.com/electron/electronjs.org/blob/605c38fcfc3b9d99fe93bed70cf5d0e1016eaa50/views/partials/head.html#L25-L31

**Comment by morrme** [comment]
So you'd like one of the images (for example https://github.com/electron/electronjs.org/blob/master/public/images/electron-icon.svg or https://github.com/electron/electronjs.org/blob/master/public/images/electron-icon.png)
added to line 30?

**Comment by HashimotoYT** [comment]
@morrme Yes, one of these images, you need to add the new meta-property `twitter:image` with a path to that icon.

**Comment by morrme** [comment]
Should the path be relative to the location in the repo or from the server? Are they one and the same?

**Comment by HashimotoYT** [comment]
@morrme I prefer using the icon from the website, since them already ready for use, you can use that URL for png version (https://www.electronjs.org/images/electron-icon.png)
