### ISSUE TITLE
Typo in Docs.

### ISSUE THREAD

**Issue by Assimilationstheorie** [electron/electronjs.org#4311]
Language: German
Link: https://www.electronjs.org/docs/tutorial/development-environment#setting-up-macos
Word: "stäter" to "später"

**Comment by erickzhao** [comment]
Hey @Assimilationstheorie, the non-English translations for our documentation are available on [CrowdIn](https://crowdin.com/project/electron). I've fixed the typo over there, so they should be available on the next pull from CrowdIn.
