### ISSUE TITLE
All App Screenshots Broken / Not Loading

### ISSUE THREAD

**Issue by sators** [electron/electronjs.org#4340]
It appears many app screenshots and logos are now broken with this message in the devtools console:

```
Refused to load the image '<URL>' because it violates the following Content Security Policy directive: "img-src 'self' data:".
```

See:
https://www.electronjs.org/apps/demoflow
https://www.electronjs.org/apps/master-tour
https://www.electronjs.org/apps/clipper
https://www.electronjs.org/apps/blink-mind-desktop

Example:
<img width="963" alt="Screen Shot 2020-08-07 at 2 04 04 PM" src="https://user-images.githubusercontent.com/649205/89674863-dce71280-d8b6-11ea-8f4f-c2bc7a3fcede.png">
<img width="826" alt="Screen Shot 2020-08-07 at 2 04 54 PM" src="https://user-images.githubusercontent.com/649205/89674911-fa1be100-d8b6-11ea-997d-e5c52d651910.png">
<img width="529" alt="Screen Shot 2020-08-07 at 2 05 07 PM" src="https://user-images.githubusercontent.com/649205/89674925-01db8580-d8b7-11ea-9b9b-a5eadef630d9.png">

**Comment by Toinane** [comment]
Hey ! I don't know if this issue is now fixed but I don't have any broken image on my side.
What is your browser? There any steps to show the issue?

**Comment by HashimotoYT** [comment]
Firstly I would say sorry for not responding to this issue, this something new in my practice.

This incident is resolved by reverting the `helmet` dependency back to `v3`, this incident only hurt folks what's open the website between 17:10 UTC and 18:17 UTC.

For fix this you can try to open `Chrome Developer Tools` -> `Network` Tab and select `Disable cache` and reload the page (You should get the new headers from server):

![image](https://user-images.githubusercontent.com/24681191/89691754-6a0b8500-d912-11ea-95cf-3e67239c20ea.png)

As another solution, you can open the browser in the `incognito mode` (Ctrl+Shift+N for Chrome, Ctrl+Shift+P for Firefox).

I maybe create the post-incident report when has more information about the incident.

Sorry for creating the troubles, we understand how are important in the availability Electron Website.

**Comment by HashimotoYT** [comment]
Closing this since the incident is was resolved, and the server should respond with the new headers after these long time.

The post-incident report is when he be ready.
