### ISSUE TITLE
Add a download CTA for Fiddle at the top of the page

### ISSUE THREAD

**Issue by bnb** [electron/electronjs.org#4484]
Currently, there's no CTA to download Fiddle at the top of the page under the logo... it's only marketing copy with the CTA at the bottom. It would be nice if the top also had a download CTA to push people to download first 👍🏻

**Comment by azhsetiawan** [comment]
Hi @erickzhao @bnb 
I wanna take and work on this.
Is it better to place download button in header or below hero/jumbotron?

**Comment by bnb** [comment]
In this case I'd say it's potentially worth trying both and let's see which visually works better.

I believe there are some other pages that have similar setups and we may be able to piggy back off their design.
