### ISSUE TITLE
Improve instructions / CTA on Spectron

### ISSUE THREAD

**Issue by bnb** [electron/electronjs.org#4537]
Currently, the Spectron instructions are a single code block that includes both the `npm install` command and actual JavaScript code example:

![image](https://user-images.githubusercontent.com/502396/94059012-daca0c00-fdaf-11ea-8fbc-0c2bb22e5069.png)

Ideally, this would be two distinct sections, with one syntax highlighted as bash and one syntax highlighted as JavaScript. Each would have unique instructions.

**Comment by stevejoachim** [comment]
Hey @bnb, I tried to address this in my PR. Is this what you were thinking?
<img width="979" alt="image" src="https://user-images.githubusercontent.com/19378484/95513524-7a7ac300-0988-11eb-9ff2-744528f6c595.png">

**Comment by bnb** [comment]
*perfect*
