### ISSUE TITLE
Include link to new Electron Discord in our Contributing docs

### ISSUE THREAD

**Issue by VerteDinde** [electron/electronjs.org#4575]
As an open source community, we want folks contributing to Electron to have access to help when they need it. To help them find those resources, we want to include a link to our new Electron Community Discord in our Contributing docs: https://github.com/electron/electron/blob/master/CONTRIBUTING.md

Acceptance Criteria:
- Includes link to Discord: https://discord.gg/H6uTh7m
- Briefly describes why a user may want to go to Electron's Discord
- Spelling/grammar looks good 👍

**Comment by the-bose** [comment]
The CONTRIBUTING.md link provided points to the CONTRIBUTING.md of electron repo and not electronjs.org repo. Where should it be added, exactly?

**Comment by MalwarePerseus** [comment]
Please check and merge PR #4593
