### ISSUE TITLE
Allow electron/apps landing page to feature apps

### ISSUE THREAD

**Issue by VerteDinde** [electron/electronjs.org#4577]
We'd like to add a "Featured" banner, allowing us to feature either a single specific Electron apps, or 2-3 specific Electron apps. 

This is a new feature, so we have some room for creative freedom. If you believe the banner should feature just one app, or have space for 2-3, we can review!

Acceptance Criteria:
- Banner should be both mobile and desktop friendly
- Banner should contain app's logo, name, a link to the app's site and a brief description of the app
- Spelling/grammar/basic code cleanliness

**Comment by abhijain2003** [comment]
I would like to work on this issue can you explain it further
![Screenshot 2022-03-11 015923](https://user-images.githubusercontent.com/91718608/157749165-8d1cdadd-5dc8-4288-ac8f-7a4d8eb7a4ca.png)


as this is the landing page so where you would like to put the feature banner

**Comment by Usman-Hassan-Gu** [comment]
I would like to contribute by working on this issue, is it okay if the featured banner is added after this section?
![Screenshot (141)](https://user-images.githubusercontent.com/55620906/161957985-79125a55-a326-44b2-8a3b-5e6c92b94269.png)
