### ISSUE TITLE
Add line numbers to the code snippets in the docs

### ISSUE THREAD

**Issue by erickzhao** [electron/electronjs.org#4586]
For better readability in the documentation, it'd be useful to have line numbers for our code snippets. Maybe limited to snippets of a certain length (i.e. to keep cleanliness for things like shell commands).

**Comment by erickzhao** [comment]
After digging through how our code works, this seems like an upstream issue for the [hubdown](https://github.com/electron/hubdown) repo, as the HTML for the code blocks is generated there.

However, this might require a refactoring of the library used to generate it, as I believe `highlight.js` doesn't support line numbers, while `prism.js` does.

**Comment by Usman-Hassan-Gu** [comment]
@erickzhao I want to contribute by working on this issue.
