### ISSUE TITLE
Add Discord Icon with Join Link to Header / Footer

### ISSUE THREAD

**Issue by bnb** [electron/electronjs.org#4591]
As we've just shipped a discord server, it'd be nice to have it in the spaces that we have other external links for "social" sites.

Specifically, it'd be nice to have it in the header and / or the footer.

We'd probably want to have it after GitHub in the header if we want it there:
![image](https://user-images.githubusercontent.com/502396/94979742-a0204c00-04f2-11eb-9749-08aafb59d605.png)

And we'd want to have it in the footer to the right of Twitter here:
![image](https://user-images.githubusercontent.com/502396/94979749-b201ef00-04f2-11eb-8e19-2b20560b6610.png)

**Comment by sumitk63** [comment]
Can i work on this?

**Comment by MalwarePerseus** [comment]
Hey There! Do I need to be assigned first, or should I just fork it and start working right away?

**Comment by VerteDinde** [comment]
Hey folks! If you'd like to take this issue, please assign yourself to it and we'll count it as assigned to you. If after ~5 days, we don't see any progress or don't hear from you, we may unassign you so that someone else has the chance to work on it. Otherwise, we'll assume you're working on it. Thanks!

**Comment by parasg1999** [comment]
@VerteDinde I don't think we can assign ourselves to the issue since it can only be done by someone with write access to this repository only.
As for this issue, since octicon doesn't supply the icon for discord, I think it'll be best to add an image for it. What do you think?

**Comment by VerteDinde** [comment]
@parasg1999 That sounds great! If you want, I can assign you to this issue and you can claim it and add an image. Thanks!

**Comment by parasg1999** [comment]
@VerteDinde That would be awesome! Will work on this issue.
