### ISSUE TITLE
Search Out of Date?

### ISSUE THREAD

**Issue by dsanders11** [electron/electronjs.org#4615]
Seems like search on the site is out of date. On the [electron/angolia-indices](https://github.com/electron/algolia-indices) repo the bot hasn't pulled an updated `electron-api.json` since September 2019. Doing a search on the site for `webContents.getBackgroundThrottling` doesn't find results despite it being in the docs.

**Comment by erickzhao** [comment]
Hey @dsanders11, thanks for the report. I've opened an issue in the `algolia-indices` repo to track this more closely (https://github.com/electron/algolia-indices/issues/220).

**Comment by vhashimotoo** [comment]
New indices have rolled.
