### ISSUE TITLE
Use PepperFlash in Electron application after 2020

### ISSUE THREAD

**Issue by akshayb25** [electron/electronjs.org#4736]
I am using pepflashplayer.dll in my electron applications. I have checked by changing the date to 2021 and it is working fine. I just wanted to know if the app is bundled now will it keep running in 2021 or it will also stop to work? Also I'll be distributing the app so is there any license required for that? Or if there is any other way I can keep using it.

**Comment by erickzhao** [comment]
Hey @akshayb25, this issue tracker is solely regarding our website's issues. Please file Electron-releated issues on the main Electron repository.

(Also, to answer your question, I don't think dropping support after 2020 is based on your computer's local time. Any version of Chrome released in 2021 will probably drop support for Flash.)
