### ISSUE TITLE
Contribution: new boilerplate

### ISSUE THREAD

**Issue by ilanolkies** [electron/electronjs.org#4771]
Hi team! I created this boilerplate for Electron + React.js + Typescript https://github.com/ilanolkies/electron-react-ts

Full features are:
- Compiles Typescript
- Builds React.js with webpack
- Runs on Electron
- Checks code syntax with ESlint and standard-with-typescript
- Tests with ts-jest and Enzyme
- Styles with Sass
- Runs lint, test and build in Github actions
- Collects Coveralls coverage reports.

Hope it can be added to the docs! Regards

**Comment by erickzhao** [comment]
Hey @ilanolkies, the boilerplates listed in our `/community` page are fetched from this repo: https://github.com/sindresorhus/awesome-electron.

Will close this issue as it's not directly linked to the website!

**Comment by ilanolkies** [comment]
Cool thanks!
