### ISSUE TITLE
Double HTML escaping in blog titles

### ISSUE THREAD

**Issue by NotWearingPants** [electron/electronjs.org#4841]
Hello 👋
I found [this blog post](https://www.electronjs.org/blog/electron-internals-node-integration) in the electronjs.org blog, and its title contains a colon, which is escaped to `&#58;`, but the HTML window title is escaped again somewhere, which results in `<title>... &amp;#58; ...</title>`
This makes the actual window title have a literal `&#58;` instead of a colon.
![image](https://user-images.githubusercontent.com/26556598/100387432-c5cc5c00-3030-11eb-85b5-96b2a2495d04.png)

This issue seems to exist in all blog posts from before 2017 which contain a colon, but since 2017 this stopped happening.

I've looked at the code and found the relevant places, but I'm not sure where the double escaping occurs.
Maybe the actual blog post file itself contains an escaped colon in the title because before 2017 you needed to escape special characters yourself?
The raw blog files don't seem to be open source so I can't check this on a local copy.

**Comment by vhashimotoo** [comment]
> The raw blog files don't seem to be open source so I can't check this on a local copy.

They are public and can be founded in https://github.com/electron/electronjs.org/tree/master/data/blog, this problem in the blog post itself, feel free to find them and send a PR.
