### ISSUE TITLE
Webview autofill for payment methods

### ISSUE THREAD

**Issue by OrganicChem** [electron/electronjs.org#5135]
Background:

**Electron version: 9.2
Mac OS 10.13**

If a Chrome user is logged into Google and **autofill** for passwords, payment methods and addresses are turned on,  when Electron triggers a webview, I would like to have autofill populate these fields in the Electron webview.

I've looked over the docs and prior issues but nothing seems to be coming up.   For in-app purchases, this is a vital feature since it reduces friction for a sale.

**Comment by erickzhao** [comment]
Hey @OrganicChem, this repository is dedicated to the electronjs.org website. If you have a feature request for the core Electron framework, please open an issue in the [electron/electron issue tracker](https://github.com/electron/electron/issues)!
