### ISSUE TITLE
A curly bracket is missing in the Spanish translation.

### ISSUE THREAD

**Issue by mrgold92** [electron/electronjs.org#5246]
In the Spanish translation, in the quick start section, in the code of the window creation, a curly bracket is missing, it is a silly thing, but it is known. 

<img width="726" alt="Captura de pantalla 2021-03-22 a las 20 13 42" src="https://user-images.githubusercontent.com/34181460/112046188-fee28c00-8b4b-11eb-99c9-ea3fb188b7c1.png">

**Comment by MarshallOfSound** [comment]
cc @erickzhao shouldn't the old translation be invalidated as soon as the english fix is in `master`?

**Comment by erickzhao** [comment]
After translations are merged into `electron/electron`, there are two separate components at work:

* `electron/i18n` needs to fetch the source content, upload the translations to CrowdIn, pull the translated content down
* `electron/electronjs.org` needs to update the `electron-i18n` package version

It seems like this data was pulled successfully into i18n: https://github.com/electron/i18n/blob/master/content/current/es-ES/docs/tutorial/quick-start.md

I've just bumped up the `electron-i18n` package version in #5248

**Comment by mrgold92** [comment]
I just checked the website and it's fixed, thanks!
