### ISSUE TITLE
fix what you continue to ignore

### ISSUE THREAD

**Issue by MacAppSuggestions** [electron/electronjs.org#5300]
you continue to ignore the problematic about https://www.electronjs.org/apps

even if i reported you at least 2-3x

revert to old UI sort mode and avoid such random application chaos.

**Comment by erickzhao** [comment]
According to GitHub search, this is the first issue you've ever opened under the `electron` org:

https://github.com/search?q=type%3Aissue+org%3Aelectron+author%3AMacAppSuggestions

@MacAppSuggestions Could you please elaborate on your request? I'm not familiar with the old sorting method.
