### ISSUE TITLE
A wrong translation at docs guide in chinese language

### ISSUE THREAD

**Issue by huijitec** [electron/electronjs.org#5393]
The Electron is a trademark, NOT "电子" in chinese, see it in below picture.

<img width="429" alt="screenshot" src="https://user-images.githubusercontent.com/55648157/118441061-353b2280-b71b-11eb-8ad6-ced9c5dfd352.png">

**Comment by erickzhao** [comment]
Hey @huijitec, I've fixed this here: https://crowdin.com/translate/electron/250328/en-zhcn#6524590

In the future, for translation corrections, feel free to contribute fixes directly onto CrowdIn: https://github.com/electron/i18n/blob/master/contributing.md
