### ISSUE TITLE
Changelog for 11.4.7?

### ISSUE THREAD

**Issue by Slapbox** [electron/electronjs.org#5404]
I thought maybe the 11.4.7 changelog was just going to take a short bit to be reflected on the site after the version was released, but after a few days it still doesn't appear. I'm wondering if there's any issue here or if I'm just being impatient?

Thanks for reading!

**Comment by erickzhao** [comment]
Fixed in https://github.com/electron/electronjs.org/pull/5402

Our current website infrastructure requires a bump on the `electron-releases` package for the releases to actually update.
