### ISSUE TITLE
Separate Classes from Modules

### ISSUE THREAD

**Issue by YurySolovyov** [electron/electronjs.org#544]
Having both modules and Classes returned by some of the methods is confusing, it would be easier to navigate the docs if they would be separated under same sections.

![image](https://cloud.githubusercontent.com/assets/2168518/19734615/de7ae2c6-9bb0-11e6-95cf-672388653f27.png)

**Comment by zeke** [comment]
Good idea. Now that we have [structured API docs](electron.atom.io/blog/2016/09/27/api-docs-json-schema), this will be easier to do on the website.

**Comment by YurySolovyov** [comment]
Seems like link got broken

**Comment by 50Wliu** [comment]
Fixed the link.  It was missing the leading `https://`, leading GitHub to think it was a relative link.

**Comment by zeke** [comment]
Thanks for fixing. And for the record I agree that this page needs work.

**Comment by YurySolovyov** [comment]
@zeke I wonder how structured API docs relate to this. I mainly thought about just re-sorting the items and  grouping them by type...
