### ISSUE TITLE
When I was loading external Web links using Browser Window, I ran into a tricky problem

### ISSUE THREAD

**Issue by yewanji** [electron/electronjs.org#5480]
I encountered a tricky problem when loading external Web links using Browser Window, as shown in the following example

const win = new BrowserWindow({ width: 800, height: 1500 })

win.loadURL('http://github.com')

Page loading properly right now, but, if the user network is not stable, jump to http://github.com/electron.js, there is a blank, excuse me I how to capture the events, and to jump to the default 404 page

**Comment by erickzhao** [comment]
Hey @yewanji, I don't think this is an issue specific to the Electron website, so I'll close it here.

If you think you've discovered a bug in Electron, please report it to the https://github.com/electron/electron issue tracker and fill out the specific form accordingly :)
