### ISSUE TITLE
fiddle site does not use max-width like the rest of the website

### ISSUE THREAD

**Issue by bnb** [electron/electronjs.org#5482]
It seems there's no max-width on the fiddle page:

![image](https://user-images.githubusercontent.com/502396/123140585-7367e800-d425-11eb-80f7-064f3b55f83e.png)

Every other page on the site does use a max-width, it seems that just wasn't applied here.

**Comment by abhijain2003** [comment]
On website where the issue is being located

**Comment by Arushisingh23** [comment]
there is some issue on the fiddle page
