### ISSUE TITLE
Link to quick start guide on community page is broken in english

### ISSUE THREAD

**Issue by Kilian** [electron/electronjs.org#5795]
>🐎 Get started building an app by reading the quick-start guide.

Both "get started" and "the quick-start guide" link to a page that returns a 404. Possibly in other languages too:https://www.electronjs.org/community

First mentioned here: https://github.com/electron/electron/issues/32122

**Comment by name-trouble** [comment]
I have the same problem.the new doc-router seems not work in server.js

**Comment by erickzhao** [comment]
This should be fixed in #5797
