### ISSUE TITLE
new releases are not being shown in releases/

### ISSUE THREAD

**Issue by ckerr** [electron/electronjs.org#5827]
https://www.electronjs.org/releases/alpha is missing v17.0.0-alpha.6 (released 2 days agoi) and v17.0.0-alpha.5 (release three weeks ag).

CC @electron/wg-ecosystem @electron/wg-releases

**Comment by erickzhao** [comment]
I believe this is just a manual merging problem. Should be close to updated with #5822 but might need another PR for the latest ones since I think Dependabot only checks once a week.

**Comment by elincoln** [comment]
@erickzhao Releases pages have stopped updating for the past few months.
