### ISSUE TITLE
Error ENOENT src not found in ....

### ISSUE THREAD

**Issue by rayisooo** [electron/electronjs.org#5854]
does anyone have any idea about this issue?

<img width="1440" alt="Screen Shot 2022-01-19 at 4 42 59 PM" src="https://user-images.githubusercontent.com/44685969/150314098-903999d1-41c4-4e27-9a8a-c5775e8c95fa.png">

here's my package.json

`{
  "name": "sneekshotbotv2",
  "productName": "Sneekshot",
  "version": "1.1.7",
  "description": "",
  "main": "src/index.js",
  "build": {
    "appId": "com.sneekshot.1999",
    "publish": "github",
    "extends": null,
    "extraResources": [
      "./extraResources/**",
      "./sDriver/**"
    ],
    "mac": {
      "icon": "assets/icons/mac/sneekshot_ICON_THREE.icns",
      "category": "com.sneekshot.bot",
      "target": [
        "zip",
        "dmg"
      ]
    },
    "win": {
      "target": "nsis",
      "icon": "build/icon.ico"
    },
    
    "nsis": {
      "oneClick": false,
      "installerIcon": "build/icon.ico",
      "uninstallerIcon": "build/icon.ico",
      "uninstallDisplayName": "Sneekshot Win Uninstaller",
      "allowToChangeInstallationDirectory": true
    }
  },
  "scripts": {
    "start": "electron-forge start",
    "package": "electron-forge package",
    "make": "electron-forge make",
    "lint": "echo \"No linting configured\"",
    "package-mac": "electron-packager . --overwrite --extra-resource=\"/Users/raymondotoadese/Desktop/sneekshotBUILDER/extraResources\"  --extra-resource=\"/Users/raymondotoadese/Desktop/sneekshotBUILDER/sDriver\" --production --asar=true --platform=darwin --arch=x64 --icon=assets/icons/mac/sneekshot_ICON_THREE.icns --prune=true --out=release-builds",
    "package-win": "electron-packager .  --overwrite --asar=true --platform=win32 --arch=ia32  --extra-resource=\"/Users/raymondotoadese/Desktop/sneekshotBUILDER/extraResources\"  --extra-resource=\"/Users/raymondotoadese/Desktop/sneekshotBUILDER/sDriver\"  --icon=assets/icons/win/SNEEKSHOT.ico --prune=true --out=release-builds --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.ProductName=\"Sneekshot\"",
    "package-linux": "electron-packager . electron-tutorial-app --overwrite --asar=true --platform=linux --arch=x64 --icon=assets/icons/png/SNEEKSHOTICON.png --prune=true --out=release-builds",
    "deploy": "electron-builder build --mac --win --publish always",
    "pack": "electron-builder --dir",
    "publish": "electron-forge publish",
    "dist": "electron-builder --x64 --win --mac",
    "gh-publish": "electron-builder -p always"
  },
  "keywords": [],
  "author": "raymondotoadese",
  "license": "MIT",
  "config": {
    "forge": {
      "packagerConfig": {},
      "makers": [
        {
          "name": "@electron-forge/maker-squirrel",
          "config": {
            "name": "Sneekshot"
          }
        },
        {
          "name": "@electron-forge/maker-zip",
          "platforms": [
            "darwin"
          ]
        },
        {
          "name": "@electron-forge/maker-deb",
          "config": {}
        },
        {
          "name": "@electron-forge/maker-rpm",
          "config": {}
        }
      ]
    }
  },
  "dependencies": {
    "bestbuy": "^2.4.1",
    "custom-electron-titlebar": "^3.2.6",
    "electron-squirrel-startup": "^1.0.0",
    "electron-updater": "^4.3.9",
    "firebase": "^8.6.8",
    "jquery": "^3.6.0",
    "node-fetch": "^2.0.0",
    "python-shell": "^3.0.0",
    "update-electron-app": "^2.0.1"
  },
  "devDependencies": {
    "@electron-forge/cli": "^6.0.0-beta.54",
    "@electron-forge/maker-deb": "^6.0.0-beta.54",
    "@electron-forge/maker-rpm": "^6.0.0-beta.54",
    "@electron-forge/maker-squirrel": "^6.0.0-beta.54",
    "@electron-forge/maker-zip": "^6.0.0-beta.54",
    "electron": "^11.5.0",
    "electron-builder": "^22.14.5"
  }
}
`

**Comment by erickzhao** [comment]
Unrelated to the website so I'll close this issue. If you would like to ask the community with help debugging your electron app, check out our discord server: https://discord.gg/electronjs
