### ISSUE TITLE
Encountered a lil bug on the Electron Fiddle Page

### ISSUE THREAD

**Issue by Jassi10000** [electron/electronjs.org#5919]
![image](https://user-images.githubusercontent.com/64856348/157676171-067a08b6-7822-4896-97f7-d0a13af47a0c.png)

On clicking the Github Icon , the page should be directed to  
https://github.com/electron/fiddle

But instead it redirects to
https://github.com/electron
which I think needs to be changed coz in the whole page there's no other reference of this page's github code , so would love to hear views of the maintainers on this , if they allow i will even contribute to this one

**Comment by malept** [comment]
The title text says "GitHub Organization" so I think this can be closed.

**Comment by Jassi10000** [comment]
> The title text says "GitHub Organization" so I think this can be closed.

ok sure no problem
