### ISSUE TITLE
electronjs.org/images CORS blocks electron-app-store

### ISSUE THREAD

**Issue by MrMYHuang** [electron/electronjs.org#5921]
I find [electron-app-store](https://github.com/Electron-Store/electron-app-store) can't show app logos correctly. I run electron-app-store for debugging and find electronjs.org/images CORS blocks it:
![image](https://user-images.githubusercontent.com/12458706/159118826-20c0ea3a-8e3a-4385-b760-e6e1bfe783e9.png)
Please fix this issue.

**Comment by abdulghanitech** [comment]
Can confirm the issue.

<img width="1395" alt="image" src="https://user-images.githubusercontent.com/18095705/169066178-dc955e83-4ab2-404d-ad75-e0a0c0cfa91f.png">
