### ISSUE TITLE
Add menu button for homepage

### ISSUE THREAD

**Issue by HyunseungLee-Travis** [electron/electronjs.org#5933]
# Issue
In mobile, the menus arr all jumbled up and hard to click.
Seems like all other pages have menu button.
However, the homepage has a lot of links which is disorganized.

# Screenshot
![Screenshot_20220505-071016_Brave - Nightly](https://user-images.githubusercontent.com/78584173/166834325-4e8f4ad5-fa8c-4dfc-a710-df198ce687be.jpg)

**Comment by HyunseungLee-Travis** [comment]
Please do! Thank you.

**Comment by HyunseungLee-Travis** [comment]
If you do, please mention it in this issue

**Comment by Jyotiraditya24** [comment]
yes I am working on it

**Comment by Jyotiraditya24** [comment]
hey I am hard time setting up this project up on local host , working on it though

**Comment by HyunseungLee-Travis** [comment]
Thanks for the updqte
