### ISSUE TITLE
Theme changes don't work on homepage

### ISSUE THREAD

**Issue by akankshaoops** [electron/electronjs.org#5945]
# Description
There is no option to choose a theme on [home page](https://www.electronjs.org/). These changes applied on other pages of the site don't work on the home page either. 

# Actual behavior

https://user-images.githubusercontent.com/66973393/188947437-8bc27c82-7f82-4cb2-8b3b-4204f5ec704d.mp4

I chose a dark theme on Electron's documentation page, but the changes don't apply on the home page. The home page also doesn't offer any way to change the theme.

# Expected behavior
Theme changes application on home page and options to choose themes across the site would help in a better user experience.

# Operating system and browser
This is happening on a Windows device, Chrome version 105.0.5195.102

**Comment by erickzhao** [comment]
these are actually two separate sites and we're mid-migration. the new code can be found at [electron/electronjs.org-new](https://github.com/electron/electronjs.org-new). closing as `wontfix` for this repo!

**Comment by akankshaoops** [comment]
Thanks for the info. Hope this will be fixed for the new site.
