### ISSUE TITLE
Filter out apps by unwanted keywords

### ISSUE THREAD

**Issue by Alhadis** [electron/electronjs.org#692]
I wasn't looking for anything in particular when I checked out [`electron.atom.io/apps`](https://electron.atom.io/apps/); I just wanted to see what sort of stuff people had done.

I noticed how many of these were Markdown editors, so I instinctively punched `NOT:markdown` into the filter-field (I'm probably too used to how GitHub [handles this](https://github.com/search?q=extension%3Ascopes+NOT+nothack&type=Code)...). I tried `-markdown`, but that didn't work either.

So, erm, randomly suggested improvement coming through. =)

**Comment by Alhadis** [comment]
In the meantime, I guess I'll use this:

~~~js
const {children} = document.querySelector(".filterable-list");
for(const e of children) /Markdown/i.test(e.textContent) && e.remove();
~~~

**Comment by db2k** [comment]
I agree, Markdown editors, chat tools and music players are flooding the app list, I thought about a filterable tag multiselect box instead of using it the Github way with search queries, since we already have the app tags setup.

(We would just have to take care, that there are not to many tags which are doubles or unnecessary.

**Comment by zeke** [comment]
The filtering is powered by [list.js](http://listjs.com/) at the moment. Maybe it has some built-in way to exclude content.

cc @javve, author of list.js

**Comment by db2k** [comment]
If there is no way to exclude directly, we could write a filter via the list.js api.
http://listjs.com/api/#filter

**Comment by zeke** [comment]
Thanks to @BinaryMuse for making this a thing in #1389 👏
