### ISSUE TITLE
Add permalinks to blog post headings

### ISSUE THREAD

**Issue by zeke** [electron/electronjs.org#708]
We should be able to deep link to content in the blog.

**Comment by db2k** [comment]
Do you mean headlines in the blog post content?

**Comment by zeke** [comment]
I mean `## Some Heading` should end up with an id like `<h2 id="some-heading">Some Heading</h2>`

**Comment by phantom-z** [comment]
@zeke  
also anchors need fix https://github.com/electron/electron.atom.io/issues/764

**Comment by zeke** [comment]
New website launched today with support for this. Markdown is processed with https://github.com/zeke/hubdown, which autogenerates DOM ids for headings.
