### ISSUE TITLE
Deprecate Basecoat and update to npm-hosted Primer

### ISSUE THREAD

**Issue by zeke** [electron/electronjs.org#757]
GitHub's internal `basecoat` stylesheet framework thing has been deprecated and folded into `primer` which is now hosted on npm instead of bower. Yayyyy!

https://github.com/primer/primer-css

Would love to get our bower deps out of the mix. @simurai do you have a sense of how easy/hard it would be to upgrade to the new stuff?

**Comment by simurai** [comment]
Probably a lot has changed, but yeah, would be nice to start using the npm version. I can give it try and see how much it breaks.

**Comment by simurai** [comment]
Gave it a try, but quite a few things (file names, mixins, variables, etc.) changed.

Chatted with @zeke and we'll keep this on hold until the next redesign comes around.

**Comment by zeke** [comment]
https://twitter.com/githubprimer/status/995061407581384704

https://github.com/primer/primer-primitives

> This is a monorepo for color, spacing, and typography primitives for use with Primer, GitHub's design system.
