### ISSUE TITLE
Use app categories

### ISSUE THREAD

**Issue by zeke** [electron/electronjs.org#759]
In https://github.com/electron/electron-apps/pull/225, @jkleinsc created a list of categories, added one to every app, and updated tests to ensure that every app always has a valid category. 🚀 

Now let's put that categorization to use on the site. Some ideas:

- Render each app's category in the apps list so folks can filter by category using the text input. For now it could be hidden from view but still part of the searchable content, like `keywords` currently is.
- Display a list of categories on the /apps page.

And as we move towards having per-app pages:

- Display the category on the app page.
- Make the category clickable to view other apps in the category.

**Comment by YurySolovyov** [comment]
I feel like alphabetical category list is more fair. it may even be collapsed initially, but as soon user starts typing the in the search we highlight+expand category name and app's name matches. Kinda like fuzzy-matcher in atom

**Comment by jkleinsc** [comment]
Categories are now live here: http://electronjs.org/apps 

This is a work in progress, so suggestions are welcome!

**Comment by YurySolovyov** [comment]
it would be nice to know what is actually matched, category, tag, app' name, etc.

**Comment by zeke** [comment]
New website landed today! https://electronjs.org/blog/new-website

@YurySolovyov feel free to open up a PR or a new issue if you want to see further changes.
