### ISSUE TITLE
App page design

### ISSUE THREAD

**Issue by jkleinsc** [electron/electronjs.org#761]
Individual app pages are now available (eg http://electronjs.org/apps/visual-comic-reader), but we need to figure out how we present the information available.  
Right now here is the information we can display

- App name
- App icon
- App screenshots with
  * Optional caption
  * Optional link when user clicks on image
- Category
- Source Code (repository link)
- Keywords 
- Downloads (if specified as assets on latest release)
- Repository ReadMe (More Details button)
- Latest Release notes (currently only displayed if there are no downloads in latest release).

suggestions welcome!

**Comment by zeke** [comment]
This is gonna be so cool! 😍 

A few ideas:

## Platform-specific download links

For apps that have release data and assets, we could display a dynamic download link for the user's operating system, like we do for the demos app on the Electron homepage:

<img width="885" alt="screen shot 2017-07-19 at 7 21 55 pm" src="https://user-images.githubusercontent.com/2289/28397635-b2f7589a-6cb7-11e7-8063-0a5723becfa3.png">

or like the GitHub Desktop site:

<img width="952" alt="screen shot 2017-07-19 at 7 23 56 pm" src="https://user-images.githubusercontent.com/2289/28397656-dbe085c4-6cb7-11e7-975c-fa3641494ed6.png">

## Colors

We also have color data for the app icons. It could be used to add accent colors to app pages to reinforce the brand.

```
> apps.find(app => app.slug === 'figma')
{ slug: 'figma',
  name: 'Figma',
  description: 'The collaborative interface design tool.',
  website: 'https://www.figma.com/',
  keywords: 
   [ 'graphics',
     'images',
     'editor',
     'svg',
     'sketch',
     'vector',
     'ui',
     'ux' ],
  icon: 'figma-icon.png',
  icon32: 'figma-icon-32.png',
  icon64: 'figma-icon-64.png',
  icon128: 'figma-icon-128.png',
  date: '2017-05-05',
  iconColors: [ '#db5e7d', '#040404', '#14c2be', '#09af70', '#442156' ],
  releases: [] }
```

**Comment by MarshallOfSound** [comment]
> Latest Release notes (currently only displayed if there are no downloads in latest release).

Would be cool to add a "release notes" button so people can see it even if there are downloads available.

> Platform-specific download links

If this goes ahead this table might help 👍 

| Platform | Type | RegExp |
|----------|------|---------|
| Windows | Installer | `/\.exe/` |
| Windows | Update Package | `/\.nupkg/` |
| Linux | Debian Package | `/\.deb/` |
| Linux | Fedora Package | `/\.rpm/` |
| Linux | Cross-dist Package | `/\.appimage/i` |
| macOS | User friendly installer | `/\.dmg/` |
| macOS | Update Package / Not-so-user-friendly installer | `/\.zip/` |
| macOS | Rare system installer | `/\.pkg/` |

Also have to be aware that on linux and windows people could be shipping multiple arches for the same platform.  So there could be `-x64.exe` and `-ia32.exe`.

**Comment by zeke** [comment]
New site landed today with app pages. See https://electronjs.org/blog/new-website#app-pages
