### ISSUE TITLE
anchor_links not working

### ISSUE THREAD

**Issue by phantom-z** [electron/electronjs.org#764]
anchor_links.html  It seems that it doesn't work or is not used? 

Can I ask why?

Thx

**Comment by MarshallOfSound** [comment]
@phantom-z It is used in the default layout 👍 

https://github.com/electron/electron.atom.io/blob/8a4df8e87134167b86fcf9c2a675ae182b072323/_layouts/default.html#L13

**Comment by phantom-z** [comment]
It is used in every page on electron.atom.io

check any header: https://electron.atom.io/blog/2017/06/01/typescript 

there is no Anchor Links, but they must be because the script is loaded

**Comment by zeke** [comment]
Must be a regression..

**Comment by MarshallOfSound** [comment]
Didn't realize this was a bug, thought it was a query about usage 😆 Reopened

**Comment by TheDancingCode** [comment]
The script is working just fine. It adds anchor links with a permalink icon to the headings under content blocks bearing a class of `docs` or `news`. Only the documentation pages have such a class, which is why the anchors only appear there.

**Comment by zeke** [comment]
Thanks, @TheDancingCode. I had a feeling this was no longer an issue but hadn't verified it. Closing.
