### ISSUE TITLE
Update awesome-electron to get latest content

### ISSUE THREAD

**Issue by SimplyCodin** [electron/electronjs.org#774]
Fix the Metadata for the community page
https://github.com/electron/electron.atom.io/blob/afe62610cd8cc156f9edb4e5b702d549272a57dc/_data/awesome_electron.json#L1372-L1378
```
 {
    "name": "electron-store",
    "href": "https://github.com/sindresorhus/electron-store",
    "description": "Simple data persistence for your Electron app or module.",
    "category": "tools",
    "subcategory": "for_electron"
  },
```
sindresorhus/electron-store#4

**Comment by zeke** [comment]
Thanks. This will get fixed the next time we pull in an update to our awesome-electron data.
