### ISSUE TITLE
Serve structured Electron releases data

### ISSUE THREAD

**Issue by zeke** [electron/electronjs.org#820]
https://atom.io/download/electron/index.json is a redirect to https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/index.json, a file which maps Electron versions numbers to their corresponding versions of V8, Chromium, Node, etc.

We should serve this data from the website instead of S3, and make it an official™ endpoint, maybe `/releases.json` or `/versions.json`.

We should also denote the beta status of a release in this data.

cc @Kilian

**Comment by Kilian** [comment]
The atom.io/download/electron/index.json link is (from my understanding) forwarded to _some_ s3 file bound to change. This file is used to generate https://github.com/Kilian/electron-to-chromium which is in turn used by browserslist to add support for Electron in babel-preset-env, eslint, autoprefixer etc. 

Browserslist has a category for 'unreleased' versions, which map nicely to the (relatively new) Beta releases we've been doing for Electron, so it would be nice to be able to add these to the file so I can add that information to electron-to-chromium.

I think electronjs.org/releases.json as a canonical/official list would be great.

**Comment by Kilian** [comment]
Looking through the site repo, there's https://github.com/electron/electron.atom.io/blob/neo/data/versions.json and https://github.com/electron/electron.atom.io/blob/neo/data/releases.json that are exposed too: http://electronjs.org/data/releases.json Versions is the same as the index.json file, releases has only the versions that are released.

**Comment by zeke** [comment]
I'm thinking maybe we should consolidate those two files (versions.json and release.json) into one.

**Comment by zeke** [comment]
We should also retire the `/docs/versions` path while we're at it, redirecting it to `/releases`

**Comment by zeke** [comment]
See also #769

**Comment by zeke** [comment]
The fix to this ended up not being a new endpoint, but a new npm module: https://github.com/electron/electron-releases
