### ISSUE TITLE
Put a CDN on it

### ISSUE THREAD

**Issue by zeke** [electron/electronjs.org#829]
electronjs.org is currently serving content straight from a Heroku dyno. We should set up a CDN to serve the static assets.

**Comment by groundwater** [comment]
Would like to keep @dead-horse and others looped in to ensure we have a China-accessible solution.

**Comment by atian25** [comment]
cc @dfguo any suggest?

**Comment by dead-horse** [comment]
I think it is mostly ok in China. : )

![image](https://user-images.githubusercontent.com/985607/33013895-7d7e4b2c-ce20-11e7-968a-590239d17c84.png)

**Comment by dfguo** [comment]
Since the site is mostly static, one quick win is to put the site behind Cloudflare.com. It only requires a simple DNS change.
