### ISSUE TITLE
Fix link to Jekyll on new site blog post

### ISSUE THREAD

**Issue by zeke** [electron/electronjs.org#851]
![screen shot 2017-11-16 at 11 47 29 am](https://user-images.githubusercontent.com/2289/32912451-f2902fd0-cac3-11e7-9cd3-853b0e170d85.png)

cc @wooorm

**Comment by wooorm** [comment]
Probably the typo on [L191](https://github.com/electron/electronjs.org/blame/78e4473a7012a352f73ca1d6f3bbfb58518aed05/data/blog/new-website.md#L191)!
