### ISSUE TITLE
404 at https://electronjs.org/apps but the page seems to be loaded correctly

### ISSUE THREAD

**Issue by tlystad24** [electron/electronjs.org#909]
Title of https://electronjs.org/apps says '404 not found', but the content is loaded correctly

**Comment by pierreneter** [comment]
Related to: #905

**Comment by zeke** [comment]
This issue was filed after I shipped a fix yesterday, so I guess the bug remains unsolved... I am not able to reproduce it.

**Comment by zeke** [comment]
I was just able to reproduce this on the homepage. I restarted the app and the problem went away. 🤔 

It seems that somehow this middleware route handler is sometimes being triggered: https://github.com/electron/electronjs.org/blob/9f557ef5e42460eea4b2f2df856775a40f4e63a8/routes/_404.js#L2
