### ISSUE TITLE
Feature apps by more objective criteria

### ISSUE THREAD

**Issue by zeke** [electron/electronjs.org#912]
There are currently 24 featured apps on the homepage. There was never a formal process by which they were selected: the list just grew organically. The list doesn't change much now because we want to be careful not to play favorites.

Let's start featuring apps by more objective criteria. Here are some ideas:

- Newly added
- Recently updated (where we have GitHub release data)
- Popular (apps that everyone has heard of: Atom, Slack, VSCode, Skype, etc.)
- Staff picks (or Community picks)
- Popular Open Source (by stars, fork count, contributor count, or some other metric)
- Awesome (apps that have made it onto the awesome-electron repo)

Hopefully this approach will level the playing field for lesser-known apps to make their way onto the homepage. If you have ideas for other ways to select apps to feature, please chime in here.

**Comment by groundwater** [comment]
We could also use this as a forcing-function to promote good app hygiene. 

e.g. Apps can only be feature if:

- they have updaters
- are on a supported electron version
- are easily downloadable (e.g. I don't have to sign up to your site first)

**Comment by Slapbox** [comment]
@zeke this is a great idea. Is there any update on this?

I noticed one of the currently featured apps hasn't been updated in several years (1Clipboard.) I reached out to them via their email a while back, but I never heard back. I believe all the other currently featured apps are very much alive.

I was planning to send an email to info@electronjs.org but then I found this issue which seemed like the most appropriate and transparent place to get in touch about this. Would there be any interest from the Electron team to include [Recollectr](http://recollectr.io) in the place of 1Clipboard until criteria for featured apps are finalized? 

I don't want to turn this into a sales pitch, so I'll just say that I think it showcases a lot of the amazing features that Electron brings to the table. Thanks to you and all of the other major contributors to Electron to making it possible!

**Comment by zeke** [comment]
> this is a great idea. Is there any update on this?

Thanks for chiming in. No updates to speak of yet. If you want to open an exploratory PR for this, feel free. Note: It might make sense to do the actual work on the https://github.com/electron/apps repo.

**Comment by BinaryMuse** [comment]
The website working group [discussed this more today](https://github.com/electron/governance/pull/59). We're going to do two things:

1. Introduce a small list of company logos (with permission) representing companies that use Electron; the idea is to demonstrate that Electron is trusted by enterprises.
2. Fully randomize the list of apps on the homepage. This will give each app an equal shot at being seen; in the future, we *may* vote to experiment with floating apps to the top, or showing them more regularly, if we can identify them as high quality apps.

**Comment by Slapbox** [comment]
@BinaryMuse that sounds like a balanced approach to me. Thanks to everybody involved in that discussion.
