### ISSUE TITLE
Improve the contact page

### ISSUE THREAD

**Issue by zeke** [electron/electronjs.org#917]
The [/contact page](https://electronjs.org/contact) currently lists a number of ways to get in touch, but does not clearly define what people should expect from each channel, or how they should interact with it:

- GitHub @electron
- Twitter @electronjs (we pretty much never respond to replies using @electronjs, in favor of our personal accounts)
- Slack atomio.slack.com (not frequented by most Electron team members)
- Discuss discuss.atom.io/c/electron (also not frequented by team members)
- Email electron@github.com (currently a dumping ground, mostly spam)

Let's make the page more actionable, like:

- To report a bug or request a feature for Electron, open an issue in electron/electron
- To report a security incident, email security@electronjs.org
- To report a violation of the Code of Conduct, email coc@electronjs.org
- To add your app to the site, open a PR on the electron-apps repo
- etc..

**Comment by ckerr** [comment]
I bed we'd get fewer info@ requests for help if we copied the content of https://github.com/electron/electron#community at the top of https://electronjs.org/community
