### ISSUE TITLE
RSS feed missing from new website

### ISSUE THREAD

**Issue by garar** [electron/electronjs.org#931]
Hello!

It seems that new website and new blog don't have RSS feed. Is it intentional? Or is it something that will be added in the future? It was quite useful.

Thanks!

**Comment by pierreneter** [comment]
It's not intentional; it will come back soon.

**Comment by pierreneter** [comment]
Duplicate of #890

**Comment by tborychowski** [comment]
currently there is no way to follow the Electron's blog.
