### ISSUE TITLE
404 for /docs/latest

### ISSUE THREAD

**Issue by Kokilagopinath** [electron/electronjs.org#933]
The following route is returning a 404 HTTP status code: /docs/latest

**Comment by zeke** [comment]
Thanks for reporting.

I think the solution is to add some redirects to server.js that account for all the URLs mentioned in this old post: https://electronjs.org/blog/electron-doumentation -- to me, that seems preferable to updating the links in the post, which would distort their historical accuracy.

**Comment by zeke** [comment]
I think we can solve this by redirecting any path that starts with `/docs/latest` to the same page minus the `/latest`, 

Example:

`/docs/latest` -> `/docs`
`/docs/latest/api/browser-window` -> `/docs/api/browser-window`
