### ISSUE TITLE
Advertise electron beta version along side stable version

### ISSUE THREAD

**Issue by vanessayuenn** [electron/electronjs.org#934]
We should show both the stable version and beta version. 

I'm thinking we can do that by adding another line on the front page (see below) where we currently show the stable version number, along with the chromium and node version used in stable, but I'm also open to another approach. 
![image](https://user-images.githubusercontent.com/6842965/33565584-820ba0f6-d8eb-11e7-97f9-42456abf22ae.png)

**Comment by groundwater** [comment]
I ran into this problem today. I know *of* the beta, but did not know what the latest version was. It's a long journey to GH releases from the front page, and most folks won't know to go there.

**Comment by zeke** [comment]
Once #960 has landed, we'll have access to this info in `req.context.releases`

```js
req.context.releases.find(release => release.npmDistTag === 'beta')
req.context.releases.find(release => release.npmDistTag === 'latest')
```

**Comment by zeke** [comment]
We should also specify that `npm i electron` gives you latest, and `npm i electron@beta` is a thing.

**Comment by zeke** [comment]
Started on a really janky version of this:

<img width="770" alt="screen shot 2017-12-22 at 1 38 55 pm" src="https://user-images.githubusercontent.com/2289/34619324-9d2d9230-f1f6-11e7-87bc-af711e00e767.png">

Will pick it up again soon and open a PR
