### ISSUE TITLE
Invalid html for each page in the docs

### ISSUE THREAD

**Issue by TheDancingCode** [electron/electronjs.org#964]
Currently, the website pulls in the docs from the `electron-i18n` package, which contains the rendered html for the original markdown files in the `electron` repo. The html is a full html document, with opening and closing `html`, `head` and `body` tags. This chunck of html is then injected into the docs layout, meaning each page of the documentation contains invalid nested `html` and `body` tags like this:
```html
<section class='page-section docs strong-headers'>
  <div class='container-narrow'>
    <html>
      <head></head>
      <body>
        <h1 id="about-electron">
          <a href="#about-electron">About Electron</a>
        </h1>
        <!-- Rest of docs content -->
      </body>
      </html>
  </div>
</section>
```
You should either change the html in the `electron-i18n` repo, or process it here before inserting it in the website.

**Comment by vanessayuenn** [comment]
Thanks for bringing this up! Personally, I'm in favor of moving the responsibility of parsing the markdown files to html from `electron-i18n` over to electronjs. That way we can have more control over the processing, in case we ever need the docs to be shown differently (e.g. snippets of docs on search result page).

**Comment by zeke** [comment]
Yeah thanks for pointing this out, @TheDancingCode. I hadn't noticed.

>  I'm in favor of moving the responsibility of parsing the markdown files to html from electron-i18n over to electronjs. 

That's fine with me, as long as the processing is done at server startup and not per request. This repo is already using the [hubdown](https://ghub.io/hubdown) module to process blog posts at startup, so it would be pretty easy to start using it for other stuff too.
