### ISSUE TITLE
App submission?

### ISSUE THREAD

**Issue by MEGAMINDMK** [electron/electronjs.org#965]
how to submit an electron app to electron-apps

**Comment by MarshallOfSound** [comment]
https://github.com/electron/electron-apps#adding-your-app

**Comment by MEGAMINDMK** [comment]
didnt help

**Comment by zeke** [comment]
@MEGAMINDMK this page should tell you everything you need to know: https://github.com/electron/electron-apps/blob/master/contributing.md

**Comment by MEGAMINDMK** [comment]
Sorry sir I tried but I still get confused during steps,is there any video on it.
Thnx,
Regards

**Comment by zeke** [comment]
What part is confusing you? If you're new to GitHub and Pull Requests, these docs should help:

- https://help.github.com/articles/about-pull-requests/
- https://help.github.com/articles/creating-a-pull-request/
- https://guides.github.com/introduction/flow/

**Comment by MEGAMINDMK** [comment]
Sir actually when I try npm push git,after that I get a message that I don't have permission

**Comment by MEGAMINDMK** [comment]
sir i have my app here which is still not accepted kindly do accept it
thnx,
regards

link to my app submission https://github.com/electron/electron-apps/pull/447
