### ISSUE TITLE
Acknowledge our translator community

### ISSUE THREAD

**Issue by zeke** [electron/electronjs.org#967]
Let's give thanks to our translators by creating a page on the website that lists their contributions. Crowdin has an (undocumented) API for fetching contributor data:

`https://api.crowdin.com/api/project/{project-identifier}/users-from-project`

**Comment by erickzhao** [comment]
Note that as of 2020, the CrowdIn V2 API has an endpoint to get all project members: https://support.crowdin.com/api/v2/#operation/api.projects.members.getMany

```
https://api.crowdin.com/api/v2/projects/{{projectId}}/members?limit=500
```
