### ISSUE TITLE
Arabic Language

### ISSUE THREAD

**Issue by Mohammed-Taher** [electron/electronjs.org#976]
Hi
Would you please enable the Arabic language.
Thank you very much.

**Comment by zeke** [comment]
Hi @Mohammed-Taher. I'd be glad to. Crowdin supports a few variants. Which one should I enable?

<img width="378" alt="screen shot 2017-12-22 at 11 59 02 am" src="https://user-images.githubusercontent.com/2289/34311022-96382f7c-e70f-11e7-8518-a4957934e083.png">

**Comment by Mohammed-Taher** [comment]
Hi zeke
Thank's a lot.
Enable the first one (Arabic) it's the generic one.

**Comment by Mohammed-Taher** [comment]
HI zeke
Have you added Arabic language to the list of the languages in electron website. I can't see it in the list.

Thank you.

**Comment by zeke** [comment]
Hey @Mohammed-Taher sorry for the delay. I just added Arabic. I wanted to land this change first: https://github.com/electron/electron-i18n/pull/206

It might take a few minutes to show up in Crowdin.
