### ISSUE TITLE
404 for /docs/tutorial/web-contents

### ISSUE THREAD

**Issue by Mikaeru69** [electron/electronjs.org#983]
The following route is returning a 404 HTTP status code: /docs/tutorial/web-contents

https://electronjs.org/docs/tutorial/keyboard-shortcuts

> L’événement `before-input-event` est émis avant d’envoyer les événements keydown et keyup dans la page. Il peut être utilisé pour intercepter et gérer des raccourcis personnalisés qui ne sont pas visibles dans le menu.

`before-input-event` links to https://electronjs.org/docs/tutorial/web-contents#event-before-input-event which returns `404 Page not found`...

**Comment by vanessayuenn** [comment]
Closing this issue as we're tracking all the 404s in #1022.
