### ISSUE TITLE
Relative README URL's do not resolve correctly

### ISSUE THREAD

**Issue by denise84** [electron/electronjs.org#986]
The following route is returning a 404 HTTP status code: /apps/docs/PlaybackAPI.md

**Comment by MarshallOfSound** [comment]
What doc are you expecting to see at that URL / where did you find that link?

**Comment by MarshallOfSound** [comment]
Thought so, it's coming from my app.

http://electronjs.org/apps/google-play-music-desktop-player

Looks like relative links from the README need to be converted to absolute URLs 👍 

/cc @zeke

**Comment by zeke** [comment]
@MarshallOfSound fixed this in https://github.com/electron/electron-apps/pull/451 -- thanks!

**Comment by denise84** [comment]
I don't know nothing about this and I didn't open this issue!!!
