### ISSUE TITLE
Improve layout of app pages

### ISSUE THREAD

**Issue by zeke** [electron/electronjs.org#995]
@donokuda made a great start at app-store-ifying the app pages in #822, but time has passed and much has changed since that WIP kicked off, so I've closed it. Let's use some of the ideas in that PR and take another shot at them:

- move more useful content "above the fold" on desktop. See https://user-images.githubusercontent.com/1174461/32741877-8bf0520a-c85c-11e7-8ee9-75a38f6ef160.png
- display the README by default
- what else?

**Comment by MarshallOfSound** [comment]
Oooh, I really like that image 👍 

If no one's already started it I can hack at that on my flight tomorrow 👍 One thing I noticed is we'll probably have to add `screenshotName` as a field to the screenshots list in yml files.
